// Code generated by Lingo for table information_schema.INNODB_FT_INDEX_TABLE - DO NOT EDIT

package qinnodbftindextable

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QInnodbFtIndexTable {
	return instance
}

func Word() path.StringPath {
	return instance.word
}

func FirstDocId() path.Int64Path {
	return instance.firstDocId
}

func LastDocId() path.Int64Path {
	return instance.lastDocId
}

func DocCount() path.Int64Path {
	return instance.docCount
}

func DocId() path.Int64Path {
	return instance.docId
}

func Position() path.Int64Path {
	return instance.position
}
