// Code generated by Lingo for table sakila.category - DO NOT EDIT

// +build !nolingo

package tcategory

import (
	"github.com/weworksandbox/lingo/expr/path"
)

var instance = New()

func T() TCategory {
	return instance
}

func CategoryId() path.Int8 {
	return instance.categoryId
}

func Name() path.String {
	return instance.name
}

func LastUpdate() path.Time {
	return instance.lastUpdate
}
