// Code generated by Lingo for table sakila.category - DO NOT EDIT

// +build !nolingo

package tcategory

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) TCategory {
	t := New()
	if alias != "" {
		t.alias = expr.Lit(alias)
	}
	return t
}

func New() TCategory {
	return TCategory{}
}

type TCategory struct {
	alias lingo.Expression
}

// lingo.Table Functions

func (t TCategory) GetTableName() string {
	return "category"
}

func (t TCategory) GetColumns() []lingo.Expression {
	return []lingo.Expression{
		t.CategoryId(),
		t.Name(),
		t.LastUpdate(),
	}
}

func (t TCategory) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return expr.Table(t).ToSQL(d)
}

func (t TCategory) GetName() lingo.Expression {
	return expr.TableName(t)
}

func (t TCategory) GetAlias() lingo.Expression {
	return t.alias
}

// Column Functions

func (t TCategory) CategoryId() expr.Int8 {
	return expr.Column(t, expr.Lit("category_id")).ToSQL
}

func (t TCategory) Name() expr.String {
	return expr.Column(t, expr.Lit("name")).ToSQL
}

func (t TCategory) LastUpdate() expr.Time {
	return expr.Column(t, expr.Lit("last_update")).ToSQL
}
