// Code generated by Lingo for table information_schema.ST_GEOMETRY_COLUMNS - DO NOT EDIT

package qstgeometrycolumns

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QStGeometryColumns {
	return instance
}

func TableCatalog() path.StringPath {
	return instance.tableCatalog
}

func TableSchema() path.StringPath {
	return instance.tableSchema
}

func TableName() path.StringPath {
	return instance.tableName
}

func ColumnName() path.StringPath {
	return instance.columnName
}

func SrsName() path.StringPath {
	return instance.srsName
}

func SrsId() path.IntPath {
	return instance.srsId
}

func GeometryTypeName() UnknownPathType {
	return instance.geometryTypeName
}
