// Code generated by Lingo for table information_schema.INNODB_FOREIGN_COLS - DO NOT EDIT

package qinnodbforeigncols

import (
	"github.com/weworksandbox/lingo/core"
	"github.com/weworksandbox/lingo/core/path"
)

func As(alias string) QInnodbForeignCols {
	return newQInnodbForeignCols(alias)
}

func New() QInnodbForeignCols {
	return newQInnodbForeignCols("")
}

func newQInnodbForeignCols(alias string) QInnodbForeignCols {
	q := QInnodbForeignCols{_alias: alias}
	q.id = path.NewStringPath(q, "ID")
	q.forColName = path.NewStringPath(q, "FOR_COL_NAME")
	q.refColName = path.NewStringPath(q, "REF_COL_NAME")
	q.pos = path.NewIntPath(q, "POS")
	return q
}

type QInnodbForeignCols struct {
	_alias     string
	id         path.StringPath
	forColName path.StringPath
	refColName path.StringPath
	pos        path.IntPath
}

// core.Table Functions

func (q QInnodbForeignCols) GetColumns() []core.Column {
	return []core.Column{
		q.id,
		q.forColName,
		q.refColName,
		q.pos,
	}
}

func (q QInnodbForeignCols) GetSQL(d core.Dialect, sql core.SQL) error {
	return path.ExpandTableWithDialect(d, q, sql)
}

func (q QInnodbForeignCols) GetAlias() string {
	return q._alias
}

func (q QInnodbForeignCols) GetName() string {
	return "INNODB_FOREIGN_COLS"
}

func (q QInnodbForeignCols) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QInnodbForeignCols) Id() path.StringPath {
	return q.id
}

func (q QInnodbForeignCols) ForColName() path.StringPath {
	return q.forColName
}

func (q QInnodbForeignCols) RefColName() path.StringPath {
	return q.refColName
}

func (q QInnodbForeignCols) Pos() path.IntPath {
	return q.pos
}
