// Code generated by Lingo for table sakila.category - DO NOT EDIT

package qcategory

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QCategory {
	return newQCategory(alias)
}

func New() QCategory {
	return newQCategory("")
}

func newQCategory(alias string) QCategory {
	q := QCategory{_alias: alias}
	q.categoryId = path.NewInt8Path(q, "category_id")
	q.name = path.NewStringPath(q, "name")
	q.lastUpdate = path.NewTimePath(q, "last_update")
	return q
}

type QCategory struct {
	_alias     string
	categoryId path.Int8
	name       path.String
	lastUpdate path.Time
}

// core.Table Functions

func (q QCategory) GetColumns() []core.Column {
	return []core.Column{
		q.categoryId,
		q.name,
		q.lastUpdate,
	}
}

func (q QCategory) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QCategory) GetAlias() string {
	return q._alias
}

func (q QCategory) GetName() string {
	return "category"
}

func (q QCategory) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QCategory) CategoryId() path.Int8 {
	return q.categoryId
}

func (q QCategory) Name() path.String {
	return q.name
}

func (q QCategory) LastUpdate() path.Time {
	return q.lastUpdate
}
