// Code generated by Lingo for table sakila.country - DO NOT EDIT

// +build !nolingo

package tcountry

import (
	"github.com/weworksandbox/lingo/expr"
)

var instance = New()

func T() TCountry {
	return instance
}

func CountryId() expr.Int16 {
	return instance.CountryId()
}

func Country() expr.String {
	return instance.Country()
}

func LastUpdate() expr.Time {
	return instance.LastUpdate()
}
