// Code generated by Lingo for table sakila.country - DO NOT EDIT

// +build !nolingo

package tcountry

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) TCountry {
	t := New()
	if alias != "" {
		t.alias = expr.Lit(alias)
	}
	return t
}

func New() TCountry {
	return TCountry{}
}

type TCountry struct {
	alias lingo.Expression
}

// lingo.Table Functions

func (t TCountry) GetTableName() string {
	return "country"
}

func (t TCountry) GetColumns() []lingo.Expression {
	return []lingo.Expression{
		t.CountryId(),
		t.Country(),
		t.LastUpdate(),
	}
}

func (t TCountry) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return expr.Table(t).ToSQL(d)
}

func (t TCountry) GetName() lingo.Expression {
	return expr.TableName(t)
}

func (t TCountry) GetAlias() lingo.Expression {
	return t.alias
}

// Column Functions

func (t TCountry) CountryId() expr.Int16 {
	return expr.Column(t, expr.Lit("country_id")).ToSQL
}

func (t TCountry) Country() expr.String {
	return expr.Column(t, expr.Lit("country")).ToSQL
}

func (t TCountry) LastUpdate() expr.Time {
	return expr.Column(t, expr.Lit("last_update")).ToSQL
}
