// Code generated by Lingo for table information_schema.STATISTICS - DO NOT EDIT

package qstatistics

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QStatistics {
	return instance
}

func TableCatalog() path.StringPath {
	return instance.tableCatalog
}

func TableSchema() path.StringPath {
	return instance.tableSchema
}

func TableName() path.StringPath {
	return instance.tableName
}

func NonUnique() path.Int64Path {
	return instance.nonUnique
}

func IndexSchema() path.StringPath {
	return instance.indexSchema
}

func IndexName() path.StringPath {
	return instance.indexName
}

func SeqInIndex() path.IntPath {
	return instance.seqInIndex
}

func ColumnName() path.StringPath {
	return instance.columnName
}

func Collation() path.StringPath {
	return instance.collation
}

func Cardinality() path.Int64Path {
	return instance.cardinality
}

func SubPart() path.Int64Path {
	return instance.subPart
}

func Packed() UnknownPathType {
	return instance.packed
}

func Nullable() path.StringPath {
	return instance.nullable
}

func IndexType() path.StringPath {
	return instance.indexType
}

func Comment() path.StringPath {
	return instance.comment
}

func IndexComment() path.StringPath {
	return instance.indexComment
}

func IsVisible() path.StringPath {
	return instance.isVisible
}

func Expression() path.StringPath {
	return instance.expression
}
