// Code generated by Lingo for table information_schema.STATISTICS - DO NOT EDIT

package qstatistics

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QStatistics {
	return instance
}

func TableCatalog() path.String {
	return instance.tableCatalog
}

func TableSchema() path.String {
	return instance.tableSchema
}

func TableName() path.String {
	return instance.tableName
}

func NonUnique() path.Int64 {
	return instance.nonUnique
}

func IndexSchema() path.String {
	return instance.indexSchema
}

func IndexName() path.String {
	return instance.indexName
}

func SeqInIndex() path.Int64 {
	return instance.seqInIndex
}

func ColumnName() path.String {
	return instance.columnName
}

func Collation() path.String {
	return instance.collation
}

func Cardinality() path.Int64 {
	return instance.cardinality
}

func SubPart() path.Int64 {
	return instance.subPart
}

func Packed() path.String {
	return instance.packed
}

func Nullable() path.String {
	return instance.nullable
}

func IndexType() path.String {
	return instance.indexType
}

func Comment() path.String {
	return instance.comment
}

func IndexComment() path.String {
	return instance.indexComment
}
