// Code generated by Lingo for table sakila.film_text - DO NOT EDIT

package qfilmtext

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QFilmText {
	return instance
}

func FilmId() path.Int16 {
	return instance.filmId
}

func Title() path.String {
	return instance.title
}

func Description() path.String {
	return instance.description
}
