// Code generated by Lingo for table information_schema.INNODB_CMP - DO NOT EDIT

package qinnodbcmp

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbCmp {
	return instance
}

func PageSize() path.IntPath {
	return instance.pageSize
}

func CompressOps() path.IntPath {
	return instance.compressOps
}

func CompressOpsOk() path.IntPath {
	return instance.compressOpsOk
}

func CompressTime() path.IntPath {
	return instance.compressTime
}

func UncompressOps() path.IntPath {
	return instance.uncompressOps
}

func UncompressTime() path.IntPath {
	return instance.uncompressTime
}
