// Code generated by Lingo for table sakila.nicer_but_slower_film_list - DO NOT EDIT

package qnicerbutslowerfilmlist

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QNicerButSlowerFilmList {
	return instance
}

func Fid() path.Int16Path {
	return instance.fid
}

func Title() path.StringPath {
	return instance.title
}

func Description() path.StringPath {
	return instance.description
}

func Category() path.StringPath {
	return instance.category
}

func Price() path.BinaryPath {
	return instance.price
}

func Length() path.Int16Path {
	return instance.length
}

func Rating() path.StringPath {
	return instance.rating
}

func Actors() path.StringPath {
	return instance.actors
}
