version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.14.2
    - 1.15.0
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: go.opentelemetry.io/otel
    versions:
    - 0.16.0
    - 0.17.0
    - 0.18.0
    - 0.19.0
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
