// Code generated by Lingo for table sakila.payment - DO NOT EDIT

// +build !nolingo

package qpayment

import "github.com/weworksandbox/lingo/pkg/core/expression/path"

var instance = New()

func Q() QPayment {
	return instance
}

func PaymentId() path.Int16 {
	return instance.paymentId
}

func CustomerId() path.Int16 {
	return instance.customerId
}

func StaffId() path.Int8 {
	return instance.staffId
}

func RentalId() path.Int {
	return instance.rentalId
}

func Amount() path.Binary {
	return instance.amount
}

func PaymentDate() path.Time {
	return instance.paymentDate
}

func LastUpdate() path.Time {
	return instance.lastUpdate
}
