// Code generated by Lingo for table sakila.payment - DO NOT EDIT

package qpayment

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QPayment {
	return newQPayment(alias)
}

func New() QPayment {
	return newQPayment("")
}

func newQPayment(alias string) QPayment {
	q := QPayment{_alias: alias}
	q.paymentId = path.NewInt16Path(q, "payment_id")
	q.customerId = path.NewInt16Path(q, "customer_id")
	q.staffId = path.NewBoolPath(q, "staff_id")
	q.rentalId = path.NewIntPath(q, "rental_id")
	q.amount = path.NewBinaryPath(q, "amount")
	q.paymentDate = path.NewTimePath(q, "payment_date")
	q.lastUpdate = path.NewTimePath(q, "last_update")
	return q
}

type QPayment struct {
	_alias      string
	paymentId   path.Int16Path
	customerId  path.Int16Path
	staffId     path.BoolPath
	rentalId    path.IntPath
	amount      path.BinaryPath
	paymentDate path.TimePath
	lastUpdate  path.TimePath
}

// core.Table Functions

func (q QPayment) GetColumns() []core.Column {
	return []core.Column{
		q.paymentId,
		q.customerId,
		q.staffId,
		q.rentalId,
		q.amount,
		q.paymentDate,
		q.lastUpdate,
	}
}

func (q QPayment) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QPayment) GetAlias() string {
	return q._alias
}

func (q QPayment) GetName() string {
	return "payment"
}

func (q QPayment) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QPayment) PaymentId() path.Int16Path {
	return q.paymentId
}

func (q QPayment) CustomerId() path.Int16Path {
	return q.customerId
}

func (q QPayment) StaffId() path.BoolPath {
	return q.staffId
}

func (q QPayment) RentalId() path.IntPath {
	return q.rentalId
}

func (q QPayment) Amount() path.BinaryPath {
	return q.amount
}

func (q QPayment) PaymentDate() path.TimePath {
	return q.paymentDate
}

func (q QPayment) LastUpdate() path.TimePath {
	return q.lastUpdate
}
