// Code generated by Lingo for table sakila.payment - DO NOT EDIT

// +build !nolingo

package qpayment

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr/path"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) QPayment {
	return newQPayment(alias)
}

func New() QPayment {
	return newQPayment("")
}

func newQPayment(alias string) QPayment {
	q := QPayment{
		_alias: alias,
	}
	q.paymentId = path.NewInt16(q, "payment_id")
	q.customerId = path.NewInt16(q, "customer_id")
	q.staffId = path.NewInt8(q, "staff_id")
	q.rentalId = path.NewInt(q, "rental_id")
	q.amount = path.NewBinary(q, "amount")
	q.paymentDate = path.NewTime(q, "payment_date")
	q.lastUpdate = path.NewTime(q, "last_update")
	return q
}

type QPayment struct {
	_alias string

	paymentId   path.Int16
	customerId  path.Int16
	staffId     path.Int8
	rentalId    path.Int
	amount      path.Binary
	paymentDate path.Time
	lastUpdate  path.Time
}

// lingo.Table Functions

func (q QPayment) GetColumns() []lingo.Column {
	return []lingo.Column{
		q.paymentId,
		q.customerId,
		q.staffId,
		q.rentalId,
		q.amount,
		q.paymentDate,
		q.lastUpdate,
	}
}

func (q QPayment) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QPayment) GetAlias() string {
	return q._alias
}

func (q QPayment) GetName() string {
	return "payment"
}

func (q QPayment) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QPayment) PaymentId() path.Int16 {
	return q.paymentId
}

func (q QPayment) CustomerId() path.Int16 {
	return q.customerId
}

func (q QPayment) StaffId() path.Int8 {
	return q.staffId
}

func (q QPayment) RentalId() path.Int {
	return q.rentalId
}

func (q QPayment) Amount() path.Binary {
	return q.amount
}

func (q QPayment) PaymentDate() path.Time {
	return q.paymentDate
}

func (q QPayment) LastUpdate() path.Time {
	return q.lastUpdate
}
