coverage:
  status:
    project:
      default:
        paths:
          # do not include generated files
          - "!expr/path"
          - "!internal/test/schema"
        target: auto
        threshold: 5%
        range: "80...100"
