// Code generated by go2go; DO NOT EDIT.


//line expression.go2:1
package lingo

//line expression.go2:1
import (
//line expression.go2:1
 "fmt"
//line expression.go2:1
 "reflect"
//line expression.go2:1
 "regexp"
//line expression.go2:1
 "strconv"
//line expression.go2:1
 "strings"
//line expression.go2:1
 "sync/atomic"
//line expression.go2:1
 "testing"
//line expression.go2:1
)

//line expression.go2:16
func VisitWithDefaultPathBuilder(e Expression) Path {
	return instantiate୦୦VisitWithBuilder୦struct୮4୮5୦lingo୮aPath(PathBuilder{}, struct{}{}, e)
}

//line expression.go2:19
type PathBuilder struct{}

//line expression.go2:20
func (b PathBuilder) Visit(ctx struct{}, e Expression) Path {
	if p, ok := e.(Path); ok {
		return p
	}
	if o, ok := e.(Operation); ok {
		for _, arg := range o.Args() {
			if p := b.Visit(ctx, arg); p != nil {
				return p
			}
		}
	}
	return nil
}

//line expression.go2:35
func VisitWithDefaultPathsBuilder(e Expression) []Path {
	return instantiate୦୦VisitWithBuilder୦୮6୮7lingo୮aPath୦୮6୮7lingo୮aPath(PathsBuilder{}, make([]Path, 0, 10), e)
}

//line expression.go2:38
type PathsBuilder struct{}

//line expression.go2:39
func (b PathsBuilder) Visit(paths []Path, e Expression) []Path {
	if p, ok := e.(Path); ok {
		paths = append(paths, p)
	}
	if o, ok := e.(Operation); ok {
		for _, arg := range o.Args() {
			paths = b.Visit(paths, arg)
		}
	}
	return paths
}

func VisitWithDefaultToStringBuilder(e Expression) string {
	return instantiate୦୦VisitWithBuilder୦lingo୮aTemplates୦string(ToStringBuilder{}, DefaultTemplates(), e)
}

//line expression.go2:54
type ToStringBuilder struct{}

//line expression.go2:55
func (b ToStringBuilder) Visit(t Templates, e Expression) string {
	if c, ok := e.(ConstantExpression); ok {
		return fmt.Sprintf("%v", c.Interface())
	}
	if o, ok := e.(Operation); ok {
		op := o.Operator()

		syntax, ok := t[op]
		if !ok {
			return fmt.Sprintf("unknown operation for operator %s and args %v", op, o.Args())
		}

		value := syntax.Replace(func(idx int) string {
			arg := o.Arg(idx)
			if arg == nil {
				return fmt.Sprintf("unknown argument at index '%d' for syntax '%s'", idx, syntax)
			}
			if argOp, ok := arg.(Operation); ok {
				return "(" + b.Visit(t, argOp) + ")"
			} else {
				return b.Visit(t, arg)
			}
		})
		return value
	}
	if p, ok := e.(Path); ok {
		parent := p.Metadata().Parent()
		elem := p.Metadata().Elem()

		if parent == nil {
			return fmt.Sprintf("%v", elem)
		}

		syntax, ok := t[p.Metadata().PathType()]
		if !ok {
			return fmt.Sprintf("unknown operation for path type %v", p.Metadata().PathType())
		}

		values := []interface{}{parent, elem}
		value := syntax.Replace(func(idx int) string {
			if idx > 2 {
				return ""
			}
			if exp, ok := values[idx].(Expression); ok {
				return b.Visit(t, exp)
			}
			return fmt.Sprintf("%v", values[idx])
		})
		return value
	}
	return b.Visit(t, e)
}

//line expression.go2:113
type Expression interface {
	Type() reflect.Type
	String() string
}

type ConstantExpression interface {
	Expression
	Interface() interface{}
}

type ParamExpression interface {
	Expression
	Name() string
	Anonymus() bool
}

//line expression.go2:136
type PredicateExpression interface {
//line expression.go2:136
 instantiate୦୦TypedExpression୦bool

				Not() PredicateExpression
}

//line expression.go2:152
type BooleanExpression interface {
//line expression.go2:152
 instantiate୦୦TypedExpression୦bool

				EqValue(b bool) BooleanExpression
				Eq(e instantiate୦୦TypedExpression୦bool,) BooleanExpression
}

//line expression.go2:163
type StringExpression interface {
//line expression.go2:163
 instantiate୦୦LiteralExpression୦string

				As(alias instantiate୦୦TypedPath୦string,) StringExpression
				Alias(alias string) StringExpression
}

//line expression.go2:8
func instantiate୦୦VisitWithBuilder୦struct୮4୮5୦lingo୮aPath(b instantiate୦୦TypedBuilder୦struct୮4୮5୦lingo୮aPath, buildCtx struct{}, e Expression) Path {
	return b.Visit(buildCtx, e)
}
//line expression.go2:8
func instantiate୦୦VisitWithBuilder୦୮6୮7lingo୮aPath୦୮6୮7lingo୮aPath(b instantiate୦୦TypedBuilder୦୮6୮7lingo୮aPath୦୮6୮7lingo୮aPath, buildCtx []Path, e Expression) []Path {
	return b.Visit(buildCtx, e)
}
//line expression.go2:8
func instantiate୦୦VisitWithBuilder୦lingo୮aTemplates୦string(b instantiate୦୦TypedBuilder୦lingo୮aTemplates୦string, buildCtx Templates, e Expression) string {
	return b.Visit(buildCtx, e)
}

//line expression.go2:10
type instantiate୦୦TypedExpression୦bool interface {
//line expression.go2:133
 Expression
}
//line expression.go2:134
type instantiate୦୦LiteralExpression୦string interface {
//line expression.go2:158
 instantiate୦୦ComparableExpression୦string

	StringValue()
}
//line expression.go2:161
type instantiate୦୦TypedPath୦string interface {
//line paths.go2:75
 instantiate୦୦TypedExpression୦string

			Path
}
//line paths.go2:78
type instantiate୦୦TypedBuilder୦struct୮4୮5୦lingo୮aPath interface {
//line expression.go2:13
 Visit(ctx struct{}, e Expression) Path
}
//line expression.go2:14
type instantiate୦୦TypedBuilder୦୮6୮7lingo୮aPath୦୮6୮7lingo୮aPath interface {
//line expression.go2:13
 Visit(ctx []Path, e Expression) []Path
}
//line expression.go2:14
type instantiate୦୦TypedBuilder୦lingo୮aTemplates୦string interface {
//line expression.go2:13
 Visit(ctx Templates, e Expression) string
}
//line expression.go2:14
type instantiate୦୦ComparableExpression୦string interface {
//line expression.go2:146
 instantiate୦୦AnyComparableExpression୦string

	GTValue(v string) BooleanExpression
	GT(e instantiate୦୦TypedExpression୦string,) BooleanExpression
}
//line expression.go2:150
type instantiate୦୦TypedExpression୦string interface {
//line expression.go2:133
 Expression
}
//line expression.go2:134
type instantiate୦୦AnyComparableExpression୦string interface {
//line expression.go2:141
 instantiate୦୦TypedExpression୦string

	Desc()
}
//line expression.go2:144
type Importable୦ int

//line expression.go2:144
var _ = fmt.Errorf
//line expression.go2:144
var _ = reflect.Append
//line expression.go2:144
var _ = regexp.Compile
//line expression.go2:144
var _ = strconv.AppendBool

//line expression.go2:144
type _ strings.Builder

//line expression.go2:144
var _ = atomic.AddInt32
//line expression.go2:144
var _ = testing.AllocsPerRun
