// Code generated by go2go; DO NOT EDIT.


//line order.go2:1
package lingo

//line order.go2:1
import (
//line order.go2:1
 "fmt"
//line order.go2:1
 "reflect"
//line order.go2:1
 "regexp"
//line order.go2:1
 "strconv"
//line order.go2:1
 "strings"
//line order.go2:1
 "sync/atomic"
//line order.go2:1
 "testing"
//line order.go2:1
)

//line order.go2:1
var _ = fmt.Errorf
//line order.go2:1
var _ = reflect.Append
//line order.go2:1
var _ = regexp.Compile
//line order.go2:1
var _ = strconv.AppendBool

//line order.go2:1
type _ strings.Builder

//line order.go2:1
var _ = atomic.AddInt32
//line order.go2:1
var _ = testing.AllocsPerRun
