// Code generated by go2go; DO NOT EDIT.


//line types.go2:1
package lingo

//line types.go2:1
import (
//line types.go2:1
 "encoding/json"
//line types.go2:1
 "fmt"
//line types.go2:1
 "reflect"
//line types.go2:1
 "strconv"
//line types.go2:1
 "strings"
//line types.go2:1
 "sync/atomic"
//line types.go2:1
 "testing"
//line types.go2:1
)

//line types.go2:9
var (
	typeInt16 = reflect.TypeOf(int16(0))
	typeBool  = reflect.TypeOf(bool(false))
)

func TypeOfInt16() reflect.Type { return typeInt16 }
func TypeOfBool() reflect.Type  { return typeBool }

//line types.go2:15
var _ = json.Compact
//line types.go2:15
var _ = fmt.Errorf
//line types.go2:15
var _ = reflect.Append
//line types.go2:15
var _ = strconv.AppendBool

//line types.go2:15
type _ strings.Builder

//line types.go2:15
var _ = atomic.AddInt32
//line types.go2:15
var _ = testing.AllocsPerRun
