// Code generated by Lingo for table information_schema.PARAMETERS - DO NOT EDIT

package qparameters

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QParameters {
	return instance
}

func SpecificCatalog() path.StringPath {
	return instance.specificCatalog
}

func SpecificSchema() path.StringPath {
	return instance.specificSchema
}

func SpecificName() path.StringPath {
	return instance.specificName
}

func OrdinalPosition() path.IntPath {
	return instance.ordinalPosition
}

func ParameterMode() path.StringPath {
	return instance.parameterMode
}

func ParameterName() path.StringPath {
	return instance.parameterName
}

func DataType() path.StringPath {
	return instance.dataType
}

func CharacterMaximumLength() path.IntPath {
	return instance.characterMaximumLength
}

func CharacterOctetLength() path.IntPath {
	return instance.characterOctetLength
}

func NumericPrecision() path.Int64Path {
	return instance.numericPrecision
}

func NumericScale() path.IntPath {
	return instance.numericScale
}

func DatetimePrecision() path.Int64Path {
	return instance.datetimePrecision
}

func CharacterSetName() path.StringPath {
	return instance.characterSetName
}

func CollationName() path.StringPath {
	return instance.collationName
}

func DtdIdentifier() path.StringPath {
	return instance.dtdIdentifier
}

func RoutineType() path.StringPath {
	return instance.routineType
}
