// Code generated by Lingo for table sakila.actor - DO NOT EDIT

// +build !nolingo

package tactor

import (
	"github.com/weworksandbox/lingo/expr"
)

var instance = New()

func T() TActor {
	return instance
}

func ActorId() expr.Int16 {
	return instance.ActorId()
}

func FirstName() expr.String {
	return instance.FirstName()
}

func LastName() expr.String {
	return instance.LastName()
}

func LastUpdate() expr.Time {
	return instance.LastUpdate()
}
