// Code generated by Lingo for table sakila.actor - DO NOT EDIT

// +build !nolingo

package tactor

import (
	"github.com/weworksandbox/lingo/expr/path"
)

var instance = New()

func T() TActor {
	return instance
}

func ActorId() path.Int16 {
	return instance.actorId
}

func FirstName() path.String {
	return instance.firstName
}

func LastName() path.String {
	return instance.lastName
}

func LastUpdate() path.Time {
	return instance.lastUpdate
}
