// Code generated by Lingo for table information_schema.INNODB_TABLES - DO NOT EDIT

package qinnodbtables

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QInnodbTables {
	return instance
}

func TableId() path.Int64Path {
	return instance.tableId
}

func Name() path.StringPath {
	return instance.name
}

func Flag() path.IntPath {
	return instance.flag
}

func NCols() path.IntPath {
	return instance.nCols
}

func Space() path.Int64Path {
	return instance.space
}

func RowFormat() path.StringPath {
	return instance.rowFormat
}

func ZipPageSize() path.IntPath {
	return instance.zipPageSize
}

func SpaceType() path.StringPath {
	return instance.spaceType
}

func InstantCols() path.IntPath {
	return instance.instantCols
}
