// Code generated by Lingo for table information_schema.PROCESSLIST - DO NOT EDIT

package qprocesslist

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QProcesslist {
	return instance
}

func Id() path.Int64 {
	return instance.id
}

func User() path.String {
	return instance.user
}

func Host() path.String {
	return instance.host
}

func Db() path.String {
	return instance.db
}

func Command() path.String {
	return instance.command
}

func Time() path.Int {
	return instance.time
}

func State() path.String {
	return instance.state
}

func Info() path.String {
	return instance.info
}
