// Code generated by Lingo for table information_schema.COLUMNS - DO NOT EDIT

package qcolumns

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QColumns {
	return instance
}

func TableCatalog() path.StringPath {
	return instance.tableCatalog
}

func TableSchema() path.StringPath {
	return instance.tableSchema
}

func TableName() path.StringPath {
	return instance.tableName
}

func ColumnName() path.StringPath {
	return instance.columnName
}

func OrdinalPosition() path.Int64Path {
	return instance.ordinalPosition
}

func ColumnDefault() path.StringPath {
	return instance.columnDefault
}

func IsNullable() path.StringPath {
	return instance.isNullable
}

func DataType() path.StringPath {
	return instance.dataType
}

func CharacterMaximumLength() path.Int64Path {
	return instance.characterMaximumLength
}

func CharacterOctetLength() path.Int64Path {
	return instance.characterOctetLength
}

func NumericPrecision() path.Int64Path {
	return instance.numericPrecision
}

func NumericScale() path.Int64Path {
	return instance.numericScale
}

func DatetimePrecision() path.Int64Path {
	return instance.datetimePrecision
}

func CharacterSetName() path.StringPath {
	return instance.characterSetName
}

func CollationName() path.StringPath {
	return instance.collationName
}

func ColumnType() path.StringPath {
	return instance.columnType
}

func ColumnKey() path.StringPath {
	return instance.columnKey
}

func Extra() path.StringPath {
	return instance.extra
}

func Privileges() path.StringPath {
	return instance.privileges
}

func ColumnComment() path.StringPath {
	return instance.columnComment
}

func GenerationExpression() path.StringPath {
	return instance.generationExpression
}
