// Code generated by Lingo for table information_schema.TABLE_PRIVILEGES - DO NOT EDIT

package qtableprivileges

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QTablePrivileges {
	return instance
}

func Grantee() path.StringPath {
	return instance.grantee
}

func TableCatalog() path.StringPath {
	return instance.tableCatalog
}

func TableSchema() path.StringPath {
	return instance.tableSchema
}

func TableName() path.StringPath {
	return instance.tableName
}

func PrivilegeType() path.StringPath {
	return instance.privilegeType
}

func IsGrantable() path.StringPath {
	return instance.isGrantable
}
