// Code generated by Lingo for table information_schema.TABLE_PRIVILEGES - DO NOT EDIT

package qtableprivileges

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QTablePrivileges {
	return newQTablePrivileges(alias)
}

func New() QTablePrivileges {
	return newQTablePrivileges("")
}

func newQTablePrivileges(alias string) QTablePrivileges {
	q := QTablePrivileges{_alias: alias}
	q.grantee = path.NewStringPath(q, "GRANTEE")
	q.tableCatalog = path.NewStringPath(q, "TABLE_CATALOG")
	q.tableSchema = path.NewStringPath(q, "TABLE_SCHEMA")
	q.tableName = path.NewStringPath(q, "TABLE_NAME")
	q.privilegeType = path.NewStringPath(q, "PRIVILEGE_TYPE")
	q.isGrantable = path.NewStringPath(q, "IS_GRANTABLE")
	return q
}

type QTablePrivileges struct {
	_alias        string
	grantee       path.String
	tableCatalog  path.String
	tableSchema   path.String
	tableName     path.String
	privilegeType path.String
	isGrantable   path.String
}

// core.Table Functions

func (q QTablePrivileges) GetColumns() []core.Column {
	return []core.Column{
		q.grantee,
		q.tableCatalog,
		q.tableSchema,
		q.tableName,
		q.privilegeType,
		q.isGrantable,
	}
}

func (q QTablePrivileges) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QTablePrivileges) GetAlias() string {
	return q._alias
}

func (q QTablePrivileges) GetName() string {
	return "TABLE_PRIVILEGES"
}

func (q QTablePrivileges) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QTablePrivileges) Grantee() path.String {
	return q.grantee
}

func (q QTablePrivileges) TableCatalog() path.String {
	return q.tableCatalog
}

func (q QTablePrivileges) TableSchema() path.String {
	return q.tableSchema
}

func (q QTablePrivileges) TableName() path.String {
	return q.tableName
}

func (q QTablePrivileges) PrivilegeType() path.String {
	return q.privilegeType
}

func (q QTablePrivileges) IsGrantable() path.String {
	return q.isGrantable
}
