// Code generated by Lingo for table sakila.sales_by_film_category - DO NOT EDIT

// +build !nolingo

package qsalesbyfilmcategory

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr/path"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) QSalesByFilmCategory {
	return newQSalesByFilmCategory(alias)
}

func New() QSalesByFilmCategory {
	return newQSalesByFilmCategory("")
}

func newQSalesByFilmCategory(alias string) QSalesByFilmCategory {
	q := QSalesByFilmCategory{
		_alias: alias,
	}
	q.category = path.NewString(q, "category")
	q.totalSales = path.NewBinary(q, "total_sales")
	return q
}

type QSalesByFilmCategory struct {
	_alias string

	category   path.String
	totalSales path.Binary
}

// lingo.Table Functions

func (q QSalesByFilmCategory) GetColumns() []lingo.Column {
	return []lingo.Column{
		q.category,
		q.totalSales,
	}
}

func (q QSalesByFilmCategory) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QSalesByFilmCategory) GetAlias() string {
	return q._alias
}

func (q QSalesByFilmCategory) GetName() string {
	return "sales_by_film_category"
}

func (q QSalesByFilmCategory) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QSalesByFilmCategory) Category() path.String {
	return q.category
}

func (q QSalesByFilmCategory) TotalSales() path.Binary {
	return q.totalSales
}
