// Code generated by an internal Lingo tool, genpaths.go - DO NOT EDIT

package path

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/expr/set"
	"github.com/weworksandbox/lingo/sql"
)

func NewBinaryWithAlias(e lingo.Table, name, alias string) Binary {
	b := Binary{
		entity: e,
		name:   name,
		alias:  alias,
	}
	b.Binary = b.ToSQL
	return b
}

func NewBinary(e lingo.Table, name string) Binary {
	return NewBinaryWithAlias(e, name, "")
}

type Binary struct {
	expr.Binary
	entity lingo.Table
	name   string
	alias  string
}

func (p Binary) GetParent() lingo.Table {
	return p.entity
}

func (p Binary) GetName() string {
	return p.name
}

func (p Binary) GetAlias() string {
	return p.alias
}

func (p Binary) As(alias string) Binary {
	p.alias = alias
	return p
}

func (p Binary) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return ExpandColumnWithDialect(d, p)
}

func (p Binary) To(value []byte) set.Set {
	return set.To(p, expr.NewValue(value))
}

func (p Binary) ToExpr(exp lingo.Expression) set.Set {
	return set.To(p, exp)
}
