// Code generated by an internal Lingo tool, genpaths.go - DO NOT EDIT

package path

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/expr/set"
	"github.com/weworksandbox/lingo/sql"
)

func NewBoolWithAlias(e lingo.Table, name, alias string) Bool {
	return Bool{
		entity: e,
		name:   name,
		alias:  alias,
	}
}

func NewBool(e lingo.Table, name string) Bool {
	return NewBoolWithAlias(e, name, "")
}

type Bool struct {
	expr.Bool
	entity lingo.Table
	name   string
	alias  string
}

func (p Bool) GetParent() lingo.Table {
	return p.entity
}

func (p Bool) GetName() string {
	return p.name
}

func (p Bool) GetAlias() string {
	return p.alias
}

func (p Bool) As(alias string) Bool {
	p.alias = alias
	return p
}

func (p Bool) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return ExpandColumnWithDialect(d, p)
}

func (p Bool) To(value bool) set.Set {
	return set.To(p, expr.NewValue(value))
}

func (p Bool) ToExpr(exp lingo.Expression) set.Set {
	return set.To(p, exp)
}
