// Code generated by an internal Lingo tool, genpaths.go - DO NOT EDIT

package path

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/expr/operator"
	"github.com/weworksandbox/lingo/expr/set"
	"github.com/weworksandbox/lingo/sql"
)

func NewFloat64WithAlias(e lingo.Table, name, alias string) Float64 {
	return Float64{
		entity: e,
		name:   name,
		alias:  alias,
	}
}

func NewFloat64(e lingo.Table, name string) Float64 {
	return NewFloat64WithAlias(e, name, "")
}

type Float64 struct {
	entity lingo.Table
	name   string
	alias  string
}

func (p Float64) GetParent() lingo.Table {
	return p.entity
}

func (p Float64) GetName() string {
	return p.name
}

func (p Float64) GetAlias() string {
	return p.alias
}

func (p Float64) As(alias string) Float64 {
	p.alias = alias
	return p
}

func (p Float64) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return ExpandColumnWithDialect(d, p)
}

func (p Float64) To(value float64) set.Set {
	return set.NewSet(p, expr.NewValue(value))
}

func (p Float64) ToExpr(exp lingo.Expression) set.Set {
	return set.NewSet(p, exp)
}

func (p Float64) Eq(value float64) operator.Binary {
	return operator.NewBinary(p, operator.Eq, expr.NewValue(value))
}

func (p Float64) EqPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.Eq, exp)
}

func (p Float64) NotEq(value float64) operator.Binary {
	return operator.NewBinary(p, operator.NotEq, expr.NewValue(value))
}

func (p Float64) NotEqPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.NotEq, exp)
}

func (p Float64) LT(value float64) operator.Binary {
	return operator.NewBinary(p, operator.LessThan, expr.NewValue(value))
}

func (p Float64) LTPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.LessThan, exp)
}

func (p Float64) LTOrEq(value float64) operator.Binary {
	return operator.NewBinary(p, operator.LessThanOrEqual, expr.NewValue(value))
}

func (p Float64) LTOrEqPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.LessThanOrEqual, exp)
}

func (p Float64) GT(value float64) operator.Binary {
	return operator.NewBinary(p, operator.GreaterThan, expr.NewValue(value))
}

func (p Float64) GTPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.GreaterThan, exp)
}

func (p Float64) GTOrEq(value float64) operator.Binary {
	return operator.NewBinary(p, operator.GreaterThanOrEqual, expr.NewValue(value))
}

func (p Float64) GTOrEqPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.GreaterThanOrEqual, exp)
}

func (p Float64) IsNull() operator.Unary {
	return operator.NewUnary(p, operator.Null)
}

func (p Float64) IsNotNull() operator.Unary {
	return operator.NewUnary(p, operator.NotNull)
}

func (p Float64) In(values ...float64) operator.Binary {
	return operator.NewBinary(p, operator.In, expr.NewParens(expr.NewValue(values)))
}

func (p Float64) InPaths(exps ...lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.In, expr.NewParens(expr.ToList(exps)))
}

func (p Float64) NotIn(values ...float64) operator.Binary {
	return operator.NewBinary(p, operator.NotIn, expr.NewParens(expr.NewValue(values)))
}

func (p Float64) NotInPaths(exps ...lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.NotIn, expr.NewParens(expr.ToList(exps)))
}

func (p Float64) Between(first, second float64) operator.Binary {
	and := expr.NewParens(expr.NewValue(first).And(expr.NewValue(second)))
	return operator.NewBinary(p, operator.Between, and)
}

func (p Float64) BetweenPaths(firstExp, secondExp lingo.Expression) operator.Binary {
	and := expr.NewParens(operator.NewBinary(firstExp, operator.And, secondExp))
	return operator.NewBinary(p, operator.Between, and)
}

func (p Float64) NotBetween(first, second float64) operator.Binary {
	and := expr.NewParens(expr.NewValue(first).And(expr.NewValue(second)))
	return operator.NewBinary(p, operator.NotBetween, and)
}

func (p Float64) NotBetweenPaths(firstExp, secondExp lingo.Expression) operator.Binary {
	and := expr.NewParens(operator.NewBinary(firstExp, operator.And, secondExp))
	return operator.NewBinary(p, operator.NotBetween, and)
}
