// Code generated by an internal Lingo tool, genpaths.go - DO NOT EDIT

package path

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/expr/operator"
	"github.com/weworksandbox/lingo/expr/set"
	"github.com/weworksandbox/lingo/sql"
)

func NewInt16WithAlias(e lingo.Table, name, alias string) Int16 {
	return Int16{
		entity: e,
		name:   name,
		alias:  alias,
	}
}

func NewInt16(e lingo.Table, name string) Int16 {
	return NewInt16WithAlias(e, name, "")
}

type Int16 struct {
	entity lingo.Table
	name   string
	alias  string
}

func (p Int16) GetParent() lingo.Table {
	return p.entity
}

func (p Int16) GetName() string {
	return p.name
}

func (p Int16) GetAlias() string {
	return p.alias
}

func (p Int16) As(alias string) Int16 {
	p.alias = alias
	return p
}

func (p Int16) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return ExpandColumnWithDialect(d, p)
}

func (p Int16) To(value int16) set.Set {
	return set.NewSet(p, expr.NewValue(value))
}

func (p Int16) ToExpr(exp lingo.Expression) set.Set {
	return set.NewSet(p, exp)
}

func (p Int16) Eq(value int16) operator.Binary {
	return operator.NewBinary(p, operator.Eq, expr.NewValue(value))
}

func (p Int16) EqPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.Eq, exp)
}

func (p Int16) NotEq(value int16) operator.Binary {
	return operator.NewBinary(p, operator.NotEq, expr.NewValue(value))
}

func (p Int16) NotEqPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.NotEq, exp)
}

func (p Int16) LT(value int16) operator.Binary {
	return operator.NewBinary(p, operator.LessThan, expr.NewValue(value))
}

func (p Int16) LTPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.LessThan, exp)
}

func (p Int16) LTOrEq(value int16) operator.Binary {
	return operator.NewBinary(p, operator.LessThanOrEqual, expr.NewValue(value))
}

func (p Int16) LTOrEqPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.LessThanOrEqual, exp)
}

func (p Int16) GT(value int16) operator.Binary {
	return operator.NewBinary(p, operator.GreaterThan, expr.NewValue(value))
}

func (p Int16) GTPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.GreaterThan, exp)
}

func (p Int16) GTOrEq(value int16) operator.Binary {
	return operator.NewBinary(p, operator.GreaterThanOrEqual, expr.NewValue(value))
}

func (p Int16) GTOrEqPath(exp lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.GreaterThanOrEqual, exp)
}

func (p Int16) IsNull() operator.Unary {
	return operator.NewUnary(p, operator.Null)
}

func (p Int16) IsNotNull() operator.Unary {
	return operator.NewUnary(p, operator.NotNull)
}

func (p Int16) In(values ...int16) operator.Binary {
	return operator.NewBinary(p, operator.In, expr.NewParens(expr.NewValue(values)))
}

func (p Int16) InPaths(exps ...lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.In, expr.NewParens(expr.ToList(exps)))
}

func (p Int16) NotIn(values ...int16) operator.Binary {
	return operator.NewBinary(p, operator.NotIn, expr.NewParens(expr.NewValue(values)))
}

func (p Int16) NotInPaths(exps ...lingo.Expression) operator.Binary {
	return operator.NewBinary(p, operator.NotIn, expr.NewParens(expr.ToList(exps)))
}

func (p Int16) Between(first, second int16) operator.Binary {
	and := expr.NewParens(expr.NewValue(first).And(expr.NewValue(second)))
	return operator.NewBinary(p, operator.Between, and)
}

func (p Int16) BetweenPaths(firstExp, secondExp lingo.Expression) operator.Binary {
	and := expr.NewParens(operator.NewBinary(firstExp, operator.And, secondExp))
	return operator.NewBinary(p, operator.Between, and)
}

func (p Int16) NotBetween(first, second int16) operator.Binary {
	and := expr.NewParens(expr.NewValue(first).And(expr.NewValue(second)))
	return operator.NewBinary(p, operator.NotBetween, and)
}

func (p Int16) NotBetweenPaths(firstExp, secondExp lingo.Expression) operator.Binary {
	and := expr.NewParens(operator.NewBinary(firstExp, operator.And, secondExp))
	return operator.NewBinary(p, operator.NotBetween, and)
}
