// Code generated by an internal Lingo tool, genpaths.go - DO NOT EDIT

package path

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/expr/operator"
	"github.com/weworksandbox/lingo/expr/set"
	"github.com/weworksandbox/lingo/sql"
)

func NewInt32WithAlias(e lingo.Table, name, alias string) Int32 {
	return Int32{
		entity: e,
		name:   name,
		alias:  alias,
	}
}

func NewInt32(e lingo.Table, name string) Int32 {
	return NewInt32WithAlias(e, name, "")
}

type Int32 struct {
	entity lingo.Table
	name   string
	alias  string
}

func (p Int32) GetParent() lingo.Table {
	return p.entity
}

func (p Int32) GetName() string {
	return p.name
}

func (p Int32) GetAlias() string {
	return p.alias
}

func (p Int32) As(alias string) Int32 {
	p.alias = alias
	return p
}

func (p Int32) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return ExpandColumnWithDialect(d, p)
}

func (p Int32) To(value int32) set.Set {
	return set.To(p, expr.NewValue(value))
}

func (p Int32) ToExpr(exp lingo.Expression) set.Set {
	return set.To(p, exp)
}

func (p Int32) Eq(value int32) operator.Binary {
	return operator.Eq(p, expr.NewValue(value))
}

func (p Int32) EqPath(exp lingo.Expression) operator.Binary {
	return operator.Eq(p, exp)
}

func (p Int32) NotEq(value int32) operator.Binary {
	return operator.NotEq(p, expr.NewValue(value))
}

func (p Int32) NotEqPath(exp lingo.Expression) operator.Binary {
	return operator.NotEq(p, exp)
}

func (p Int32) LT(value int32) operator.Binary {
	return operator.LessThan(p, expr.NewValue(value))
}

func (p Int32) LTPath(exp lingo.Expression) operator.Binary {
	return operator.LessThan(p, exp)
}

func (p Int32) LTOrEq(value int32) operator.Binary {
	return operator.LessThanOrEqual(p, expr.NewValue(value))
}

func (p Int32) LTOrEqPath(exp lingo.Expression) operator.Binary {
	return operator.LessThanOrEqual(p, exp)
}

func (p Int32) GT(value int32) operator.Binary {
	return operator.GreaterThan(p, expr.NewValue(value))
}

func (p Int32) GTPath(exp lingo.Expression) operator.Binary {
	return operator.GreaterThan(p, exp)
}

func (p Int32) GTOrEq(value int32) operator.Binary {
	return operator.GreaterThanOrEqual(p, expr.NewValue(value))
}

func (p Int32) GTOrEqPath(exp lingo.Expression) operator.Binary {
	return operator.GreaterThanOrEqual(p, exp)
}

func (p Int32) IsNull() operator.Unary {
	return operator.IsNull(p)
}

func (p Int32) IsNotNull() operator.Unary {
	return operator.IsNotNull(p)
}

func (p Int32) In(values ...int32) operator.Binary {
	return operator.In(p, expr.NewParens(expr.NewValue(values)))
}

func (p Int32) InPaths(exps ...lingo.Expression) operator.Binary {
	return operator.In(p, expr.NewParens(expr.ToList(exps)))
}

func (p Int32) NotIn(values ...int32) operator.Binary {
	return operator.NotIn(p, expr.NewParens(expr.NewValue(values)))
}

func (p Int32) NotInPaths(exps ...lingo.Expression) operator.Binary {
	return operator.NotIn(p, expr.NewParens(expr.ToList(exps)))
}

func (p Int32) Between(first, second int32) operator.Binary {
	return operator.Between(p, expr.NewValue(first), expr.NewValue(second))
}

func (p Int32) BetweenPaths(first, second lingo.Expression) operator.Binary {
	return operator.Between(p, first, second)
}

func (p Int32) NotBetween(first, second int32) operator.Binary {
	return operator.NotBetween(p, expr.NewValue(first), expr.NewValue(second))
}

func (p Int32) NotBetweenPaths(first, second lingo.Expression) operator.Binary {
	return operator.NotBetween(p, first, second)
}
