// Code generated by Lingo for table information_schema.INNODB_INDEXES - DO NOT EDIT

package qinnodbindexes

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QInnodbIndexes {
	return instance
}

func IndexId() path.Int64Path {
	return instance.indexId
}

func Name() path.StringPath {
	return instance.name
}

func TableId() path.Int64Path {
	return instance.tableId
}

func Type() path.IntPath {
	return instance.__type
}

func NFields() path.IntPath {
	return instance.nFields
}

func PageNo() path.IntPath {
	return instance.pageNo
}

func Space() path.IntPath {
	return instance.space
}

func MergeThreshold() path.IntPath {
	return instance.mergeThreshold
}
