// Code generated by Lingo for table information_schema.INNODB_SYS_TABLESTATS - DO NOT EDIT

package qinnodbsystablestats

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbSysTablestats {
	return instance
}

func TableId() path.Int64 {
	return instance.tableId
}

func Name() path.String {
	return instance.name
}

func StatsInitialized() path.String {
	return instance.statsInitialized
}

func NumRows() path.Int64 {
	return instance.numRows
}

func ClustIndexSize() path.Int64 {
	return instance.clustIndexSize
}

func OtherIndexSize() path.Int64 {
	return instance.otherIndexSize
}

func ModifiedCounter() path.Int64 {
	return instance.modifiedCounter
}

func Autoinc() path.Int64 {
	return instance.autoinc
}

func RefCount() path.Int {
	return instance.refCount
}
