// Code generated by Lingo for table information_schema.INNODB_SYS_TABLESTATS - DO NOT EDIT

package qinnodbsystablestats

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QInnodbSysTablestats {
	return newQInnodbSysTablestats(alias)
}

func New() QInnodbSysTablestats {
	return newQInnodbSysTablestats("")
}

func newQInnodbSysTablestats(alias string) QInnodbSysTablestats {
	q := QInnodbSysTablestats{_alias: alias}
	q.tableId = path.NewInt64Path(q, "TABLE_ID")
	q.name = path.NewStringPath(q, "NAME")
	q.statsInitialized = path.NewStringPath(q, "STATS_INITIALIZED")
	q.numRows = path.NewInt64Path(q, "NUM_ROWS")
	q.clustIndexSize = path.NewInt64Path(q, "CLUST_INDEX_SIZE")
	q.otherIndexSize = path.NewInt64Path(q, "OTHER_INDEX_SIZE")
	q.modifiedCounter = path.NewInt64Path(q, "MODIFIED_COUNTER")
	q.autoinc = path.NewInt64Path(q, "AUTOINC")
	q.refCount = path.NewIntPath(q, "REF_COUNT")
	return q
}

type QInnodbSysTablestats struct {
	_alias           string
	tableId          path.Int64
	name             path.String
	statsInitialized path.String
	numRows          path.Int64
	clustIndexSize   path.Int64
	otherIndexSize   path.Int64
	modifiedCounter  path.Int64
	autoinc          path.Int64
	refCount         path.Int
}

// core.Table Functions

func (q QInnodbSysTablestats) GetColumns() []core.Column {
	return []core.Column{
		q.tableId,
		q.name,
		q.statsInitialized,
		q.numRows,
		q.clustIndexSize,
		q.otherIndexSize,
		q.modifiedCounter,
		q.autoinc,
		q.refCount,
	}
}

func (q QInnodbSysTablestats) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QInnodbSysTablestats) GetAlias() string {
	return q._alias
}

func (q QInnodbSysTablestats) GetName() string {
	return "INNODB_SYS_TABLESTATS"
}

func (q QInnodbSysTablestats) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QInnodbSysTablestats) TableId() path.Int64 {
	return q.tableId
}

func (q QInnodbSysTablestats) Name() path.String {
	return q.name
}

func (q QInnodbSysTablestats) StatsInitialized() path.String {
	return q.statsInitialized
}

func (q QInnodbSysTablestats) NumRows() path.Int64 {
	return q.numRows
}

func (q QInnodbSysTablestats) ClustIndexSize() path.Int64 {
	return q.clustIndexSize
}

func (q QInnodbSysTablestats) OtherIndexSize() path.Int64 {
	return q.otherIndexSize
}

func (q QInnodbSysTablestats) ModifiedCounter() path.Int64 {
	return q.modifiedCounter
}

func (q QInnodbSysTablestats) Autoinc() path.Int64 {
	return q.autoinc
}

func (q QInnodbSysTablestats) RefCount() path.Int {
	return q.refCount
}
