// Code generated by Lingo for table information_schema.COLLATIONS - DO NOT EDIT

package qcollations

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QCollations {
	return instance
}

func CollationName() path.String {
	return instance.collationName
}

func CharacterSetName() path.String {
	return instance.characterSetName
}

func Id() path.Int64 {
	return instance.id
}

func IsDefault() path.String {
	return instance.isDefault
}

func IsCompiled() path.String {
	return instance.isCompiled
}

func Sortlen() path.Int64 {
	return instance.sortlen
}
