// Code generated by Lingo for table information_schema.COLUMN_PRIVILEGES - DO NOT EDIT

package qcolumnprivileges

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QColumnPrivileges {
	return instance
}

func Grantee() path.StringPath {
	return instance.grantee
}

func TableCatalog() path.StringPath {
	return instance.tableCatalog
}

func TableSchema() path.StringPath {
	return instance.tableSchema
}

func TableName() path.StringPath {
	return instance.tableName
}

func ColumnName() path.StringPath {
	return instance.columnName
}

func PrivilegeType() path.StringPath {
	return instance.privilegeType
}

func IsGrantable() path.StringPath {
	return instance.isGrantable
}
