// Code generated by Lingo for table information_schema.COLUMN_PRIVILEGES - DO NOT EDIT

package qcolumnprivileges

import (
	"github.com/weworksandbox/lingo/core"
	"github.com/weworksandbox/lingo/core/path"
)

func As(alias string) QColumnPrivileges {
	return newQColumnPrivileges(alias)
}

func New() QColumnPrivileges {
	return newQColumnPrivileges("")
}

func newQColumnPrivileges(alias string) QColumnPrivileges {
	q := QColumnPrivileges{_alias: alias}
	q.grantee = path.NewStringPath(q, "GRANTEE")
	q.tableCatalog = path.NewStringPath(q, "TABLE_CATALOG")
	q.tableSchema = path.NewStringPath(q, "TABLE_SCHEMA")
	q.tableName = path.NewStringPath(q, "TABLE_NAME")
	q.columnName = path.NewStringPath(q, "COLUMN_NAME")
	q.privilegeType = path.NewStringPath(q, "PRIVILEGE_TYPE")
	q.isGrantable = path.NewStringPath(q, "IS_GRANTABLE")
	return q
}

type QColumnPrivileges struct {
	_alias        string
	grantee       path.StringPath
	tableCatalog  path.StringPath
	tableSchema   path.StringPath
	tableName     path.StringPath
	columnName    path.StringPath
	privilegeType path.StringPath
	isGrantable   path.StringPath
}

// core.Table Functions

func (q QColumnPrivileges) GetColumns() []core.Column {
	return []core.Column{
		q.grantee,
		q.tableCatalog,
		q.tableSchema,
		q.tableName,
		q.columnName,
		q.privilegeType,
		q.isGrantable,
	}
}

func (q QColumnPrivileges) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QColumnPrivileges) GetAlias() string {
	return q._alias
}

func (q QColumnPrivileges) GetName() string {
	return "COLUMN_PRIVILEGES"
}

func (q QColumnPrivileges) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QColumnPrivileges) Grantee() path.StringPath {
	return q.grantee
}

func (q QColumnPrivileges) TableCatalog() path.StringPath {
	return q.tableCatalog
}

func (q QColumnPrivileges) TableSchema() path.StringPath {
	return q.tableSchema
}

func (q QColumnPrivileges) TableName() path.StringPath {
	return q.tableName
}

func (q QColumnPrivileges) ColumnName() path.StringPath {
	return q.columnName
}

func (q QColumnPrivileges) PrivilegeType() path.StringPath {
	return q.privilegeType
}

func (q QColumnPrivileges) IsGrantable() path.StringPath {
	return q.isGrantable
}
