// Code generated by Lingo for table information_schema.KEYWORDS - DO NOT EDIT

package qkeywords

import (
	"github.com/weworksandbox/lingo/core"
	"github.com/weworksandbox/lingo/core/path"
)

func As(alias string) QKeywords {
	return newQKeywords(alias)
}

func New() QKeywords {
	return newQKeywords("")
}

func newQKeywords(alias string) QKeywords {
	q := QKeywords{_alias: alias}
	q.word = path.NewStringPath(q, "WORD")
	q.reserved = path.NewIntPath(q, "RESERVED")
	return q
}

type QKeywords struct {
	_alias   string
	word     path.StringPath
	reserved path.IntPath
}

// core.Table Functions

func (q QKeywords) GetColumns() []core.Column {
	return []core.Column{
		q.word,
		q.reserved,
	}
}

func (q QKeywords) GetSQL(d core.Dialect, sql core.SQL) error {
	return path.ExpandTableWithDialect(d, q, sql)
}

func (q QKeywords) GetAlias() string {
	return q._alias
}

func (q QKeywords) GetName() string {
	return "KEYWORDS"
}

func (q QKeywords) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QKeywords) Word() path.StringPath {
	return q.word
}

func (q QKeywords) Reserved() path.IntPath {
	return q.reserved
}
