// Code generated by Lingo for table information_schema.CHECK_CONSTRAINTS - DO NOT EDIT

package qcheckconstraints

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QCheckConstraints {
	return instance
}

func ConstraintCatalog() path.StringPath {
	return instance.constraintCatalog
}

func ConstraintSchema() path.StringPath {
	return instance.constraintSchema
}

func ConstraintName() path.StringPath {
	return instance.constraintName
}

func CheckClause() path.StringPath {
	return instance.checkClause
}
