// Code generated by Lingo for table information_schema.INNODB_SYS_INDEXES - DO NOT EDIT

package qinnodbsysindexes

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QInnodbSysIndexes {
	return newQInnodbSysIndexes(alias)
}

func New() QInnodbSysIndexes {
	return newQInnodbSysIndexes("")
}

func newQInnodbSysIndexes(alias string) QInnodbSysIndexes {
	q := QInnodbSysIndexes{_alias: alias}
	q.indexId = path.NewInt64Path(q, "INDEX_ID")
	q.name = path.NewStringPath(q, "NAME")
	q.tableId = path.NewInt64Path(q, "TABLE_ID")
	q.__type = path.NewIntPath(q, "TYPE")
	q.nFields = path.NewIntPath(q, "N_FIELDS")
	q.pageNo = path.NewIntPath(q, "PAGE_NO")
	q.space = path.NewIntPath(q, "SPACE")
	q.mergeThreshold = path.NewIntPath(q, "MERGE_THRESHOLD")
	return q
}

type QInnodbSysIndexes struct {
	_alias         string
	indexId        path.Int64
	name           path.String
	tableId        path.Int64
	__type         path.Int
	nFields        path.Int
	pageNo         path.Int
	space          path.Int
	mergeThreshold path.Int
}

// core.Table Functions

func (q QInnodbSysIndexes) GetColumns() []core.Column {
	return []core.Column{
		q.indexId,
		q.name,
		q.tableId,
		q.__type,
		q.nFields,
		q.pageNo,
		q.space,
		q.mergeThreshold,
	}
}

func (q QInnodbSysIndexes) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QInnodbSysIndexes) GetAlias() string {
	return q._alias
}

func (q QInnodbSysIndexes) GetName() string {
	return "INNODB_SYS_INDEXES"
}

func (q QInnodbSysIndexes) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QInnodbSysIndexes) IndexId() path.Int64 {
	return q.indexId
}

func (q QInnodbSysIndexes) Name() path.String {
	return q.name
}

func (q QInnodbSysIndexes) TableId() path.Int64 {
	return q.tableId
}

func (q QInnodbSysIndexes) Type() path.Int {
	return q.__type
}

func (q QInnodbSysIndexes) NFields() path.Int {
	return q.nFields
}

func (q QInnodbSysIndexes) PageNo() path.Int {
	return q.pageNo
}

func (q QInnodbSysIndexes) Space() path.Int {
	return q.space
}

func (q QInnodbSysIndexes) MergeThreshold() path.Int {
	return q.mergeThreshold
}
