// Code generated by Lingo for table sakila.customer - DO NOT EDIT

// +build !nolingo

package qcustomer

import (
	"github.com/weworksandbox/lingo/expr/path"
)

var instance = New()

func Q() QCustomer {
	return instance
}

func CustomerId() path.Int16 {
	return instance.customerId
}

func StoreId() path.Int8 {
	return instance.storeId
}

func FirstName() path.String {
	return instance.firstName
}

func LastName() path.String {
	return instance.lastName
}

func Email() path.String {
	return instance.email
}

func AddressId() path.Int16 {
	return instance.addressId
}

func Active() path.Int8 {
	return instance.active
}

func CreateDate() path.Time {
	return instance.createDate
}

func LastUpdate() path.Time {
	return instance.lastUpdate
}
