// Code generated by Lingo for table sakila.language - DO NOT EDIT

package qlanguage

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QLanguage {
	return instance
}

func LanguageId() path.Int8Path {
	return instance.languageId
}

func Name() path.StringPath {
	return instance.name
}

func LastUpdate() path.TimePath {
	return instance.lastUpdate
}
