// Code generated by Lingo for table sakila.language - DO NOT EDIT

// +build !nolingo

package qlanguage

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
	"github.com/weworksandbox/lingo/pkg/core/sql"
)

func As(alias string) QLanguage {
	return newQLanguage(alias)
}

func New() QLanguage {
	return newQLanguage("")
}

func newQLanguage(alias string) QLanguage {
	q := QLanguage{_alias: alias}
	q.languageId = path.NewInt8(q, "language_id")
	q.name = path.NewString(q, "name")
	q.lastUpdate = path.NewTime(q, "last_update")
	return q
}

type QLanguage struct {
	_alias     string
	languageId path.Int8
	name       path.String
	lastUpdate path.Time
}

// core.Table Functions

func (q QLanguage) GetColumns() []core.Column {
	return []core.Column{
		q.languageId,
		q.name,
		q.lastUpdate,
	}
}

func (q QLanguage) ToSQL(d core.Dialect) (sql.Data, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QLanguage) GetAlias() string {
	return q._alias
}

func (q QLanguage) GetName() string {
	return "language"
}

func (q QLanguage) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QLanguage) LanguageId() path.Int8 {
	return q.languageId
}

func (q QLanguage) Name() path.String {
	return q.name
}

func (q QLanguage) LastUpdate() path.Time {
	return q.lastUpdate
}
