// Code generated by Lingo for table sakila.actor_info - DO NOT EDIT

package qactorinfo

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QActorInfo {
	return instance
}

func ActorId() path.Int16Path {
	return instance.actorId
}

func FirstName() path.StringPath {
	return instance.firstName
}

func LastName() path.StringPath {
	return instance.lastName
}

func FilmInfo() path.StringPath {
	return instance.filmInfo
}
