// Code generated by Lingo for table sakila.store - DO NOT EDIT

package qstore

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QStore {
	return newQStore(alias)
}

func New() QStore {
	return newQStore("")
}

func newQStore(alias string) QStore {
	q := QStore{_alias: alias}
	q.storeId = path.NewInt8Path(q, "store_id")
	q.managerStaffId = path.NewInt8Path(q, "manager_staff_id")
	q.addressId = path.NewInt16Path(q, "address_id")
	q.lastUpdate = path.NewTimePath(q, "last_update")
	return q
}

type QStore struct {
	_alias         string
	storeId        path.Int8
	managerStaffId path.Int8
	addressId      path.Int16
	lastUpdate     path.Time
}

// core.Table Functions

func (q QStore) GetColumns() []core.Column {
	return []core.Column{
		q.storeId,
		q.managerStaffId,
		q.addressId,
		q.lastUpdate,
	}
}

func (q QStore) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QStore) GetAlias() string {
	return q._alias
}

func (q QStore) GetName() string {
	return "store"
}

func (q QStore) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QStore) StoreId() path.Int8 {
	return q.storeId
}

func (q QStore) ManagerStaffId() path.Int8 {
	return q.managerStaffId
}

func (q QStore) AddressId() path.Int16 {
	return q.addressId
}

func (q QStore) LastUpdate() path.Time {
	return q.lastUpdate
}
