// Code generated by Lingo for table sakila.store - DO NOT EDIT

// +build !nolingo

package qstore

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr/path"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) QStore {
	return newQStore(alias)
}

func New() QStore {
	return newQStore("")
}

func newQStore(alias string) QStore {
	q := QStore{
		_alias: alias,
	}
	q.storeId = path.NewInt8(q, "store_id")
	q.managerStaffId = path.NewInt8(q, "manager_staff_id")
	q.addressId = path.NewInt16(q, "address_id")
	q.lastUpdate = path.NewTime(q, "last_update")
	return q
}

type QStore struct {
	_alias string

	storeId        path.Int8
	managerStaffId path.Int8
	addressId      path.Int16
	lastUpdate     path.Time
}

// lingo.Table Functions

func (q QStore) GetColumns() []lingo.Column {
	return []lingo.Column{
		q.storeId,
		q.managerStaffId,
		q.addressId,
		q.lastUpdate,
	}
}

func (q QStore) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QStore) GetAlias() string {
	return q._alias
}

func (q QStore) GetName() string {
	return "store"
}

func (q QStore) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QStore) StoreId() path.Int8 {
	return q.storeId
}

func (q QStore) ManagerStaffId() path.Int8 {
	return q.managerStaffId
}

func (q QStore) AddressId() path.Int16 {
	return q.addressId
}

func (q QStore) LastUpdate() path.Time {
	return q.lastUpdate
}
