// Code generated by Lingo for table sakila.staff - DO NOT EDIT

// +build !nolingo

package tstaff

import (
	"github.com/weworksandbox/lingo/expr"
)

var instance = New()

func T() TStaff {
	return instance
}

func StaffId() expr.Int8 {
	return instance.StaffId()
}

func FirstName() expr.String {
	return instance.FirstName()
}

func LastName() expr.String {
	return instance.LastName()
}

func AddressId() expr.Int16 {
	return instance.AddressId()
}

func Picture() expr.UnsupportedType {
	return instance.Picture()
}

func Email() expr.String {
	return instance.Email()
}

func StoreId() expr.Int8 {
	return instance.StoreId()
}

func Active() expr.Int8 {
	return instance.Active()
}

func Username() expr.String {
	return instance.Username()
}

func Password() expr.String {
	return instance.Password()
}

func LastUpdate() expr.Time {
	return instance.LastUpdate()
}
