// Code generated by Lingo for table information_schema.INNODB_BUFFER_POOL_STATS - DO NOT EDIT

package qinnodbbufferpoolstats

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbBufferPoolStats {
	return instance
}

func PoolId() path.Int64Path {
	return instance.poolId
}

func PoolSize() path.Int64Path {
	return instance.poolSize
}

func FreeBuffers() path.Int64Path {
	return instance.freeBuffers
}

func DatabasePages() path.Int64Path {
	return instance.databasePages
}

func OldDatabasePages() path.Int64Path {
	return instance.oldDatabasePages
}

func ModifiedDatabasePages() path.Int64Path {
	return instance.modifiedDatabasePages
}

func PendingDecompress() path.Int64Path {
	return instance.pendingDecompress
}

func PendingReads() path.Int64Path {
	return instance.pendingReads
}

func PendingFlushLru() path.Int64Path {
	return instance.pendingFlushLru
}

func PendingFlushList() path.Int64Path {
	return instance.pendingFlushList
}

func PagesMadeYoung() path.Int64Path {
	return instance.pagesMadeYoung
}

func PagesNotMadeYoung() path.Int64Path {
	return instance.pagesNotMadeYoung
}

func PagesMadeYoungRate() path.Float64Path {
	return instance.pagesMadeYoungRate
}

func PagesMadeNotYoungRate() path.Float64Path {
	return instance.pagesMadeNotYoungRate
}

func NumberPagesRead() path.Int64Path {
	return instance.numberPagesRead
}

func NumberPagesCreated() path.Int64Path {
	return instance.numberPagesCreated
}

func NumberPagesWritten() path.Int64Path {
	return instance.numberPagesWritten
}

func PagesReadRate() path.Float64Path {
	return instance.pagesReadRate
}

func PagesCreateRate() path.Float64Path {
	return instance.pagesCreateRate
}

func PagesWrittenRate() path.Float64Path {
	return instance.pagesWrittenRate
}

func NumberPagesGet() path.Int64Path {
	return instance.numberPagesGet
}

func HitRate() path.Int64Path {
	return instance.hitRate
}

func YoungMakePerThousandGets() path.Int64Path {
	return instance.youngMakePerThousandGets
}

func NotYoungMakePerThousandGets() path.Int64Path {
	return instance.notYoungMakePerThousandGets
}

func NumberPagesReadAhead() path.Int64Path {
	return instance.numberPagesReadAhead
}

func NumberReadAheadEvicted() path.Int64Path {
	return instance.numberReadAheadEvicted
}

func ReadAheadRate() path.Float64Path {
	return instance.readAheadRate
}

func ReadAheadEvictedRate() path.Float64Path {
	return instance.readAheadEvictedRate
}

func LruIoTotal() path.Int64Path {
	return instance.lruIoTotal
}

func LruIoCurrent() path.Int64Path {
	return instance.lruIoCurrent
}

func UncompressTotal() path.Int64Path {
	return instance.uncompressTotal
}

func UncompressCurrent() path.Int64Path {
	return instance.uncompressCurrent
}
