// Code generated by Lingo for table information_schema.TABLES - DO NOT EDIT

package qtables

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QTables {
	return instance
}

func TableCatalog() path.String {
	return instance.tableCatalog
}

func TableSchema() path.String {
	return instance.tableSchema
}

func TableName() path.String {
	return instance.tableName
}

func TableType() path.String {
	return instance.tableType
}

func Engine() path.String {
	return instance.engine
}

func Version() path.Int64 {
	return instance.version
}

func RowFormat() path.String {
	return instance.rowFormat
}

func TableRows() path.Int64 {
	return instance.tableRows
}

func AvgRowLength() path.Int64 {
	return instance.avgRowLength
}

func DataLength() path.Int64 {
	return instance.dataLength
}

func MaxDataLength() path.Int64 {
	return instance.maxDataLength
}

func IndexLength() path.Int64 {
	return instance.indexLength
}

func DataFree() path.Int64 {
	return instance.dataFree
}

func AutoIncrement() path.Int64 {
	return instance.autoIncrement
}

func CreateTime() path.Time {
	return instance.createTime
}

func UpdateTime() path.Time {
	return instance.updateTime
}

func CheckTime() path.Time {
	return instance.checkTime
}

func TableCollation() path.String {
	return instance.tableCollation
}

func Checksum() path.Int64 {
	return instance.checksum
}

func CreateOptions() path.String {
	return instance.createOptions
}

func TableComment() path.String {
	return instance.tableComment
}
