// Code generated by Lingo for table information_schema.INNODB_SYS_VIRTUAL - DO NOT EDIT

package qinnodbsysvirtual

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbSysVirtual {
	return instance
}

func TableId() path.Int64Path {
	return instance.tableId
}

func Pos() path.IntPath {
	return instance.pos
}

func BasePos() path.IntPath {
	return instance.basePos
}
