// Code generated by Lingo for table sakila.staff_list - DO NOT EDIT

package qstafflist

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
	"github.com/weworksandbox/lingo/pkg/core/sql"
)

func As(alias string) QStaffList {
	return newQStaffList(alias)
}

func New() QStaffList {
	return newQStaffList("")
}

func newQStaffList(alias string) QStaffList {
	q := QStaffList{_alias: alias}
	q.id = path.NewInt8(q, "ID")
	q.name = path.NewString(q, "name")
	q.address = path.NewString(q, "address")
	q.zipCode = path.NewString(q, "zip code")
	q.phone = path.NewString(q, "phone")
	q.city = path.NewString(q, "city")
	q.country = path.NewString(q, "country")
	q.sid = path.NewInt8(q, "SID")
	return q
}

type QStaffList struct {
	_alias  string
	id      path.Int8
	name    path.String
	address path.String
	zipCode path.String
	phone   path.String
	city    path.String
	country path.String
	sid     path.Int8
}

// core.Table Functions

func (q QStaffList) GetColumns() []core.Column {
	return []core.Column{
		q.id,
		q.name,
		q.address,
		q.zipCode,
		q.phone,
		q.city,
		q.country,
		q.sid,
	}
}

func (q QStaffList) ToSQL(d core.Dialect) (sql.Data, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QStaffList) GetAlias() string {
	return q._alias
}

func (q QStaffList) GetName() string {
	return "staff_list"
}

func (q QStaffList) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QStaffList) Id() path.Int8 {
	return q.id
}

func (q QStaffList) Name() path.String {
	return q.name
}

func (q QStaffList) Address() path.String {
	return q.address
}

func (q QStaffList) ZipCode() path.String {
	return q.zipCode
}

func (q QStaffList) Phone() path.String {
	return q.phone
}

func (q QStaffList) City() path.String {
	return q.city
}

func (q QStaffList) Country() path.String {
	return q.country
}

func (q QStaffList) Sid() path.Int8 {
	return q.sid
}
