// Code generated by Lingo for table sakila.film - DO NOT EDIT

package qfilm

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QFilm {
	return newQFilm(alias)
}

func New() QFilm {
	return newQFilm("")
}

func newQFilm(alias string) QFilm {
	q := QFilm{_alias: alias}
	q.filmId = path.NewInt16Path(q, "film_id")
	q.title = path.NewStringPath(q, "title")
	q.description = path.NewStringPath(q, "description")
	q.releaseYear = path.NewUnsupportedPath(q, "release_year")
	q.languageId = path.NewBoolPath(q, "language_id")
	q.originalLanguageId = path.NewBoolPath(q, "original_language_id")
	q.rentalDuration = path.NewBoolPath(q, "rental_duration")
	q.rentalRate = path.NewBinaryPath(q, "rental_rate")
	q.length = path.NewInt16Path(q, "length")
	q.replacementCost = path.NewBinaryPath(q, "replacement_cost")
	q.rating = path.NewStringPath(q, "rating")
	q.specialFeatures = path.NewStringPath(q, "special_features")
	q.lastUpdate = path.NewTimePath(q, "last_update")
	return q
}

type QFilm struct {
	_alias             string
	filmId             path.Int16Path
	title              path.StringPath
	description        path.StringPath
	releaseYear        path.UnsupportedPath
	languageId         path.BoolPath
	originalLanguageId path.BoolPath
	rentalDuration     path.BoolPath
	rentalRate         path.BinaryPath
	length             path.Int16Path
	replacementCost    path.BinaryPath
	rating             path.StringPath
	specialFeatures    path.StringPath
	lastUpdate         path.TimePath
}

// core.Table Functions

func (q QFilm) GetColumns() []core.Column {
	return []core.Column{
		q.filmId,
		q.title,
		q.description,
		q.releaseYear,
		q.languageId,
		q.originalLanguageId,
		q.rentalDuration,
		q.rentalRate,
		q.length,
		q.replacementCost,
		q.rating,
		q.specialFeatures,
		q.lastUpdate,
	}
}

func (q QFilm) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QFilm) GetAlias() string {
	return q._alias
}

func (q QFilm) GetName() string {
	return "film"
}

func (q QFilm) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QFilm) FilmId() path.Int16Path {
	return q.filmId
}

func (q QFilm) Title() path.StringPath {
	return q.title
}

func (q QFilm) Description() path.StringPath {
	return q.description
}

func (q QFilm) ReleaseYear() path.UnsupportedPath {
	return q.releaseYear
}

func (q QFilm) LanguageId() path.BoolPath {
	return q.languageId
}

func (q QFilm) OriginalLanguageId() path.BoolPath {
	return q.originalLanguageId
}

func (q QFilm) RentalDuration() path.BoolPath {
	return q.rentalDuration
}

func (q QFilm) RentalRate() path.BinaryPath {
	return q.rentalRate
}

func (q QFilm) Length() path.Int16Path {
	return q.length
}

func (q QFilm) ReplacementCost() path.BinaryPath {
	return q.replacementCost
}

func (q QFilm) Rating() path.StringPath {
	return q.rating
}

func (q QFilm) SpecialFeatures() path.StringPath {
	return q.specialFeatures
}

func (q QFilm) LastUpdate() path.TimePath {
	return q.lastUpdate
}
