// Code generated by Lingo for table information_schema.INNODB_FT_BEING_DELETED - DO NOT EDIT

package qinnodbftbeingdeleted

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QInnodbFtBeingDeleted {
	return instance
}

func DocId() path.Int64Path {
	return instance.docId
}
