// Code generated by Lingo for table sakila.payment - DO NOT EDIT

// +build !nolingo

package tpayment

import (
	"github.com/weworksandbox/lingo/expr"
)

var instance = New()

func T() TPayment {
	return instance
}

func PaymentId() expr.Int16 {
	return instance.PaymentId()
}

func CustomerId() expr.Int16 {
	return instance.CustomerId()
}

func StaffId() expr.Int8 {
	return instance.StaffId()
}

func RentalId() expr.Int {
	return instance.RentalId()
}

func Amount() expr.Binary {
	return instance.Amount()
}

func PaymentDate() expr.Time {
	return instance.PaymentDate()
}

func LastUpdate() expr.Time {
	return instance.LastUpdate()
}
