// Code generated by Lingo for table sakila.customer - DO NOT EDIT

// +build !nolingo

package tcustomer

import (
	"github.com/weworksandbox/lingo/expr"
)

var instance = New()

func T() TCustomer {
	return instance
}

func CustomerId() expr.Int16 {
	return instance.CustomerId()
}

func StoreId() expr.Int8 {
	return instance.StoreId()
}

func FirstName() expr.String {
	return instance.FirstName()
}

func LastName() expr.String {
	return instance.LastName()
}

func Email() expr.String {
	return instance.Email()
}

func AddressId() expr.Int16 {
	return instance.AddressId()
}

func Active() expr.Int8 {
	return instance.Active()
}

func CreateDate() expr.Time {
	return instance.CreateDate()
}

func LastUpdate() expr.Time {
	return instance.LastUpdate()
}
