// Code generated by Lingo for table sakila.customer - DO NOT EDIT

// +build !nolingo

package tcustomer

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) TCustomer {
	t := New()
	if alias != "" {
		t.alias = expr.Lit(alias)
	}
	return t
}

func New() TCustomer {
	return TCustomer{}
}

type TCustomer struct {
	alias lingo.Expression
}

// lingo.Table Functions

func (t TCustomer) GetTableName() string {
	return "customer"
}

func (t TCustomer) GetColumns() []lingo.Expression {
	return []lingo.Expression{
		t.CustomerId(),
		t.StoreId(),
		t.FirstName(),
		t.LastName(),
		t.Email(),
		t.AddressId(),
		t.Active(),
		t.CreateDate(),
		t.LastUpdate(),
	}
}

func (t TCustomer) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return expr.Table(t).ToSQL(d)
}

func (t TCustomer) GetName() lingo.Expression {
	return expr.TableName(t)
}

func (t TCustomer) GetAlias() lingo.Expression {
	return t.alias
}

// Column Functions

func (t TCustomer) CustomerId() expr.Int16 {
	return expr.Column(t, expr.Lit("customer_id")).ToSQL
}

func (t TCustomer) StoreId() expr.Int8 {
	return expr.Column(t, expr.Lit("store_id")).ToSQL
}

func (t TCustomer) FirstName() expr.String {
	return expr.Column(t, expr.Lit("first_name")).ToSQL
}

func (t TCustomer) LastName() expr.String {
	return expr.Column(t, expr.Lit("last_name")).ToSQL
}

func (t TCustomer) Email() expr.String {
	return expr.Column(t, expr.Lit("email")).ToSQL
}

func (t TCustomer) AddressId() expr.Int16 {
	return expr.Column(t, expr.Lit("address_id")).ToSQL
}

func (t TCustomer) Active() expr.Int8 {
	return expr.Column(t, expr.Lit("active")).ToSQL
}

func (t TCustomer) CreateDate() expr.Time {
	return expr.Column(t, expr.Lit("create_date")).ToSQL
}

func (t TCustomer) LastUpdate() expr.Time {
	return expr.Column(t, expr.Lit("last_update")).ToSQL
}
