// Code generated by Lingo for table sakila.customer - DO NOT EDIT

package qcustomer

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QCustomer {
	return instance
}

func CustomerId() path.Int16Path {
	return instance.customerId
}

func StoreId() path.BoolPath {
	return instance.storeId
}

func FirstName() path.StringPath {
	return instance.firstName
}

func LastName() path.StringPath {
	return instance.lastName
}

func Email() path.StringPath {
	return instance.email
}

func AddressId() path.Int16Path {
	return instance.addressId
}

func Active() path.BoolPath {
	return instance.active
}

func CreateDate() path.TimePath {
	return instance.createDate
}

func LastUpdate() path.TimePath {
	return instance.lastUpdate
}
