// Code generated by Lingo for table information_schema.REFERENTIAL_CONSTRAINTS - DO NOT EDIT

package qreferentialconstraints

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QReferentialConstraints {
	return instance
}

func ConstraintCatalog() path.StringPath {
	return instance.constraintCatalog
}

func ConstraintSchema() path.StringPath {
	return instance.constraintSchema
}

func ConstraintName() path.StringPath {
	return instance.constraintName
}

func UniqueConstraintCatalog() path.StringPath {
	return instance.uniqueConstraintCatalog
}

func UniqueConstraintSchema() path.StringPath {
	return instance.uniqueConstraintSchema
}

func UniqueConstraintName() path.StringPath {
	return instance.uniqueConstraintName
}

func MatchOption() path.StringPath {
	return instance.matchOption
}

func UpdateRule() path.StringPath {
	return instance.updateRule
}

func DeleteRule() path.StringPath {
	return instance.deleteRule
}

func TableName() path.StringPath {
	return instance.tableName
}

func ReferencedTableName() path.StringPath {
	return instance.referencedTableName
}
