// Code generated by Lingo for table information_schema.INNODB_COLUMNS - DO NOT EDIT

package qinnodbcolumns

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QInnodbColumns {
	return instance
}

func TableId() path.Int64Path {
	return instance.tableId
}

func Name() path.StringPath {
	return instance.name
}

func Pos() path.Int64Path {
	return instance.pos
}

func Mtype() path.IntPath {
	return instance.mtype
}

func Prtype() path.IntPath {
	return instance.prtype
}

func Len() path.IntPath {
	return instance.len
}

func HasDefault() path.IntPath {
	return instance.hasDefault
}

func DefaultValue() UnknownPathType {
	return instance.defaultValue
}
