// Code generated by Lingo for table information_schema.INNODB_SYS_TABLESPACES - DO NOT EDIT

package qinnodbsystablespaces

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QInnodbSysTablespaces {
	return newQInnodbSysTablespaces(alias)
}

func New() QInnodbSysTablespaces {
	return newQInnodbSysTablespaces("")
}

func newQInnodbSysTablespaces(alias string) QInnodbSysTablespaces {
	q := QInnodbSysTablespaces{_alias: alias}
	q.space = path.NewIntPath(q, "SPACE")
	q.name = path.NewStringPath(q, "NAME")
	q.flag = path.NewIntPath(q, "FLAG")
	q.fileFormat = path.NewStringPath(q, "FILE_FORMAT")
	q.rowFormat = path.NewStringPath(q, "ROW_FORMAT")
	q.pageSize = path.NewIntPath(q, "PAGE_SIZE")
	q.zipPageSize = path.NewIntPath(q, "ZIP_PAGE_SIZE")
	q.spaceType = path.NewStringPath(q, "SPACE_TYPE")
	q.fsBlockSize = path.NewIntPath(q, "FS_BLOCK_SIZE")
	q.fileSize = path.NewInt64Path(q, "FILE_SIZE")
	q.allocatedSize = path.NewInt64Path(q, "ALLOCATED_SIZE")
	return q
}

type QInnodbSysTablespaces struct {
	_alias        string
	space         path.Int
	name          path.String
	flag          path.Int
	fileFormat    path.String
	rowFormat     path.String
	pageSize      path.Int
	zipPageSize   path.Int
	spaceType     path.String
	fsBlockSize   path.Int
	fileSize      path.Int64
	allocatedSize path.Int64
}

// core.Table Functions

func (q QInnodbSysTablespaces) GetColumns() []core.Column {
	return []core.Column{
		q.space,
		q.name,
		q.flag,
		q.fileFormat,
		q.rowFormat,
		q.pageSize,
		q.zipPageSize,
		q.spaceType,
		q.fsBlockSize,
		q.fileSize,
		q.allocatedSize,
	}
}

func (q QInnodbSysTablespaces) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QInnodbSysTablespaces) GetAlias() string {
	return q._alias
}

func (q QInnodbSysTablespaces) GetName() string {
	return "INNODB_SYS_TABLESPACES"
}

func (q QInnodbSysTablespaces) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QInnodbSysTablespaces) Space() path.Int {
	return q.space
}

func (q QInnodbSysTablespaces) Name() path.String {
	return q.name
}

func (q QInnodbSysTablespaces) Flag() path.Int {
	return q.flag
}

func (q QInnodbSysTablespaces) FileFormat() path.String {
	return q.fileFormat
}

func (q QInnodbSysTablespaces) RowFormat() path.String {
	return q.rowFormat
}

func (q QInnodbSysTablespaces) PageSize() path.Int {
	return q.pageSize
}

func (q QInnodbSysTablespaces) ZipPageSize() path.Int {
	return q.zipPageSize
}

func (q QInnodbSysTablespaces) SpaceType() path.String {
	return q.spaceType
}

func (q QInnodbSysTablespaces) FsBlockSize() path.Int {
	return q.fsBlockSize
}

func (q QInnodbSysTablespaces) FileSize() path.Int64 {
	return q.fileSize
}

func (q QInnodbSysTablespaces) AllocatedSize() path.Int64 {
	return q.allocatedSize
}
