// Code generated by Lingo for table information_schema.PARTITIONS - DO NOT EDIT

package qpartitions

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QPartitions {
	return instance
}

func TableCatalog() path.String {
	return instance.tableCatalog
}

func TableSchema() path.String {
	return instance.tableSchema
}

func TableName() path.String {
	return instance.tableName
}

func PartitionName() path.String {
	return instance.partitionName
}

func SubpartitionName() path.String {
	return instance.subpartitionName
}

func PartitionOrdinalPosition() path.Int64 {
	return instance.partitionOrdinalPosition
}

func SubpartitionOrdinalPosition() path.Int64 {
	return instance.subpartitionOrdinalPosition
}

func PartitionMethod() path.String {
	return instance.partitionMethod
}

func SubpartitionMethod() path.String {
	return instance.subpartitionMethod
}

func PartitionExpression() path.String {
	return instance.partitionExpression
}

func SubpartitionExpression() path.String {
	return instance.subpartitionExpression
}

func PartitionDescription() path.String {
	return instance.partitionDescription
}

func TableRows() path.Int64 {
	return instance.tableRows
}

func AvgRowLength() path.Int64 {
	return instance.avgRowLength
}

func DataLength() path.Int64 {
	return instance.dataLength
}

func MaxDataLength() path.Int64 {
	return instance.maxDataLength
}

func IndexLength() path.Int64 {
	return instance.indexLength
}

func DataFree() path.Int64 {
	return instance.dataFree
}

func CreateTime() path.Time {
	return instance.createTime
}

func UpdateTime() path.Time {
	return instance.updateTime
}

func CheckTime() path.Time {
	return instance.checkTime
}

func Checksum() path.Int64 {
	return instance.checksum
}

func PartitionComment() path.String {
	return instance.partitionComment
}

func Nodegroup() path.String {
	return instance.nodegroup
}

func TablespaceName() path.String {
	return instance.tablespaceName
}
