// Code generated by Lingo for table information_schema.TABLE_CONSTRAINTS - DO NOT EDIT

package qtableconstraints

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QTableConstraints {
	return instance
}

func ConstraintCatalog() path.StringPath {
	return instance.constraintCatalog
}

func ConstraintSchema() path.StringPath {
	return instance.constraintSchema
}

func ConstraintName() path.StringPath {
	return instance.constraintName
}

func TableSchema() path.StringPath {
	return instance.tableSchema
}

func TableName() path.StringPath {
	return instance.tableName
}

func ConstraintType() path.StringPath {
	return instance.constraintType
}
