// Code generated by Lingo for table information_schema.GLOBAL_STATUS - DO NOT EDIT

package qglobalstatus

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QGlobalStatus {
	return instance
}

func VariableName() path.StringPath {
	return instance.variableName
}

func VariableValue() path.StringPath {
	return instance.variableValue
}
