// Code generated by Lingo for table information_schema.COLUMN_STATISTICS - DO NOT EDIT

package qcolumnstatistics

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QColumnStatistics {
	return instance
}

func SchemaName() path.StringPath {
	return instance.schemaName
}

func TableName() path.StringPath {
	return instance.tableName
}

func ColumnName() path.StringPath {
	return instance.columnName
}

func Histogram() path.JSONPath {
	return instance.histogram
}
