// Code generated by Lingo for schema information_schema - DO NOT EDIT

package qinformationschema

var instance = schema{_name: "information_schema"}

func GetSchema() *schema {
	return &instance
}

type schema struct {
	_name string
}

func (s schema) GetName() string {
	return s._name
}
