// Code generated by Lingo for table information_schema.TRIGGERS - DO NOT EDIT

package qtriggers

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QTriggers {
	return instance
}

func TriggerCatalog() path.String {
	return instance.triggerCatalog
}

func TriggerSchema() path.String {
	return instance.triggerSchema
}

func TriggerName() path.String {
	return instance.triggerName
}

func EventManipulation() path.String {
	return instance.eventManipulation
}

func EventObjectCatalog() path.String {
	return instance.eventObjectCatalog
}

func EventObjectSchema() path.String {
	return instance.eventObjectSchema
}

func EventObjectTable() path.String {
	return instance.eventObjectTable
}

func ActionOrder() path.Int64 {
	return instance.actionOrder
}

func ActionCondition() path.String {
	return instance.actionCondition
}

func ActionStatement() path.String {
	return instance.actionStatement
}

func ActionOrientation() path.String {
	return instance.actionOrientation
}

func ActionTiming() path.String {
	return instance.actionTiming
}

func ActionReferenceOldTable() path.String {
	return instance.actionReferenceOldTable
}

func ActionReferenceNewTable() path.String {
	return instance.actionReferenceNewTable
}

func ActionReferenceOldRow() path.String {
	return instance.actionReferenceOldRow
}

func ActionReferenceNewRow() path.String {
	return instance.actionReferenceNewRow
}

func Created() path.Time {
	return instance.created
}

func SqlMode() path.String {
	return instance.sqlMode
}

func Definer() path.String {
	return instance.definer
}

func CharacterSetClient() path.String {
	return instance.characterSetClient
}

func CollationConnection() path.String {
	return instance.collationConnection
}

func DatabaseCollation() path.String {
	return instance.databaseCollation
}
