// Code generated by Lingo for table information_schema.INNODB_FT_DELETED - DO NOT EDIT

package qinnodbftdeleted

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbFtDeleted {
	return instance
}

func DocId() path.Int64 {
	return instance.docId
}
