// Code generated by Lingo for table information_schema.INNODB_FT_DELETED - DO NOT EDIT

package qinnodbftdeleted

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QInnodbFtDeleted {
	return newQInnodbFtDeleted(alias)
}

func New() QInnodbFtDeleted {
	return newQInnodbFtDeleted("")
}

func newQInnodbFtDeleted(alias string) QInnodbFtDeleted {
	q := QInnodbFtDeleted{_alias: alias}
	q.docId = path.NewInt64Path(q, "DOC_ID")
	return q
}

type QInnodbFtDeleted struct {
	_alias string
	docId  path.Int64
}

// core.Table Functions

func (q QInnodbFtDeleted) GetColumns() []core.Column {
	return []core.Column{
		q.docId,
	}
}

func (q QInnodbFtDeleted) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QInnodbFtDeleted) GetAlias() string {
	return q._alias
}

func (q QInnodbFtDeleted) GetName() string {
	return "INNODB_FT_DELETED"
}

func (q QInnodbFtDeleted) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QInnodbFtDeleted) DocId() path.Int64 {
	return q.docId
}
