// Code generated by Lingo for table sakila.actor_info - DO NOT EDIT

// +build !nolingo

package tactorinfo

import (
	"github.com/weworksandbox/lingo/expr"
)

var instance = New()

func T() TActorInfo {
	return instance
}

func ActorId() expr.Int16 {
	return instance.ActorId()
}

func FirstName() expr.String {
	return instance.FirstName()
}

func LastName() expr.String {
	return instance.LastName()
}

func FilmInfo() expr.String {
	return instance.FilmInfo()
}
