// Code generated by Lingo for table sakila.actor_info - DO NOT EDIT

// +build !nolingo

package tactorinfo

import (
	"github.com/weworksandbox/lingo/expr/path"
)

var instance = New()

func T() TActorInfo {
	return instance
}

func ActorId() path.Int16 {
	return instance.actorId
}

func FirstName() path.String {
	return instance.firstName
}

func LastName() path.String {
	return instance.lastName
}

func FilmInfo() path.String {
	return instance.filmInfo
}
