// Code generated by Lingo for table information_schema.INNODB_BUFFER_PAGE - DO NOT EDIT

package qinnodbbufferpage

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbBufferPage {
	return instance
}

func PoolId() path.Int64 {
	return instance.poolId
}

func BlockId() path.Int64 {
	return instance.blockId
}

func Space() path.Int64 {
	return instance.space
}

func PageNumber() path.Int64 {
	return instance.pageNumber
}

func PageType() path.String {
	return instance.pageType
}

func FlushType() path.Int64 {
	return instance.flushType
}

func FixCount() path.Int64 {
	return instance.fixCount
}

func IsHashed() path.String {
	return instance.isHashed
}

func NewestModification() path.Int64 {
	return instance.newestModification
}

func OldestModification() path.Int64 {
	return instance.oldestModification
}

func AccessTime() path.Int64 {
	return instance.accessTime
}

func TableName() path.String {
	return instance.tableName
}

func IndexName() path.String {
	return instance.indexName
}

func NumberRecords() path.Int64 {
	return instance.numberRecords
}

func DataSize() path.Int64 {
	return instance.dataSize
}

func CompressedSize() path.Int64 {
	return instance.compressedSize
}

func PageState() path.String {
	return instance.pageState
}

func IoFix() path.String {
	return instance.ioFix
}

func IsOld() path.String {
	return instance.isOld
}

func FreePageClock() path.Int64 {
	return instance.freePageClock
}
