// Code generated by Lingo for table information_schema.INNODB_BUFFER_PAGE - DO NOT EDIT

package qinnodbbufferpage

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QInnodbBufferPage {
	return newQInnodbBufferPage(alias)
}

func New() QInnodbBufferPage {
	return newQInnodbBufferPage("")
}

func newQInnodbBufferPage(alias string) QInnodbBufferPage {
	q := QInnodbBufferPage{_alias: alias}
	q.poolId = path.NewInt64Path(q, "POOL_ID")
	q.blockId = path.NewInt64Path(q, "BLOCK_ID")
	q.space = path.NewInt64Path(q, "SPACE")
	q.pageNumber = path.NewInt64Path(q, "PAGE_NUMBER")
	q.pageType = path.NewStringPath(q, "PAGE_TYPE")
	q.flushType = path.NewInt64Path(q, "FLUSH_TYPE")
	q.fixCount = path.NewInt64Path(q, "FIX_COUNT")
	q.isHashed = path.NewStringPath(q, "IS_HASHED")
	q.newestModification = path.NewInt64Path(q, "NEWEST_MODIFICATION")
	q.oldestModification = path.NewInt64Path(q, "OLDEST_MODIFICATION")
	q.accessTime = path.NewInt64Path(q, "ACCESS_TIME")
	q.tableName = path.NewStringPath(q, "TABLE_NAME")
	q.indexName = path.NewStringPath(q, "INDEX_NAME")
	q.numberRecords = path.NewInt64Path(q, "NUMBER_RECORDS")
	q.dataSize = path.NewInt64Path(q, "DATA_SIZE")
	q.compressedSize = path.NewInt64Path(q, "COMPRESSED_SIZE")
	q.pageState = path.NewStringPath(q, "PAGE_STATE")
	q.ioFix = path.NewStringPath(q, "IO_FIX")
	q.isOld = path.NewStringPath(q, "IS_OLD")
	q.freePageClock = path.NewInt64Path(q, "FREE_PAGE_CLOCK")
	return q
}

type QInnodbBufferPage struct {
	_alias             string
	poolId             path.Int64
	blockId            path.Int64
	space              path.Int64
	pageNumber         path.Int64
	pageType           path.String
	flushType          path.Int64
	fixCount           path.Int64
	isHashed           path.String
	newestModification path.Int64
	oldestModification path.Int64
	accessTime         path.Int64
	tableName          path.String
	indexName          path.String
	numberRecords      path.Int64
	dataSize           path.Int64
	compressedSize     path.Int64
	pageState          path.String
	ioFix              path.String
	isOld              path.String
	freePageClock      path.Int64
}

// core.Table Functions

func (q QInnodbBufferPage) GetColumns() []core.Column {
	return []core.Column{
		q.poolId,
		q.blockId,
		q.space,
		q.pageNumber,
		q.pageType,
		q.flushType,
		q.fixCount,
		q.isHashed,
		q.newestModification,
		q.oldestModification,
		q.accessTime,
		q.tableName,
		q.indexName,
		q.numberRecords,
		q.dataSize,
		q.compressedSize,
		q.pageState,
		q.ioFix,
		q.isOld,
		q.freePageClock,
	}
}

func (q QInnodbBufferPage) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QInnodbBufferPage) GetAlias() string {
	return q._alias
}

func (q QInnodbBufferPage) GetName() string {
	return "INNODB_BUFFER_PAGE"
}

func (q QInnodbBufferPage) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QInnodbBufferPage) PoolId() path.Int64 {
	return q.poolId
}

func (q QInnodbBufferPage) BlockId() path.Int64 {
	return q.blockId
}

func (q QInnodbBufferPage) Space() path.Int64 {
	return q.space
}

func (q QInnodbBufferPage) PageNumber() path.Int64 {
	return q.pageNumber
}

func (q QInnodbBufferPage) PageType() path.String {
	return q.pageType
}

func (q QInnodbBufferPage) FlushType() path.Int64 {
	return q.flushType
}

func (q QInnodbBufferPage) FixCount() path.Int64 {
	return q.fixCount
}

func (q QInnodbBufferPage) IsHashed() path.String {
	return q.isHashed
}

func (q QInnodbBufferPage) NewestModification() path.Int64 {
	return q.newestModification
}

func (q QInnodbBufferPage) OldestModification() path.Int64 {
	return q.oldestModification
}

func (q QInnodbBufferPage) AccessTime() path.Int64 {
	return q.accessTime
}

func (q QInnodbBufferPage) TableName() path.String {
	return q.tableName
}

func (q QInnodbBufferPage) IndexName() path.String {
	return q.indexName
}

func (q QInnodbBufferPage) NumberRecords() path.Int64 {
	return q.numberRecords
}

func (q QInnodbBufferPage) DataSize() path.Int64 {
	return q.dataSize
}

func (q QInnodbBufferPage) CompressedSize() path.Int64 {
	return q.compressedSize
}

func (q QInnodbBufferPage) PageState() path.String {
	return q.pageState
}

func (q QInnodbBufferPage) IoFix() path.String {
	return q.ioFix
}

func (q QInnodbBufferPage) IsOld() path.String {
	return q.isOld
}

func (q QInnodbBufferPage) FreePageClock() path.Int64 {
	return q.freePageClock
}
