// Code generated by Lingo for table information_schema.TABLESPACES - DO NOT EDIT

package qtablespaces

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QTablespaces {
	return instance
}

func TablespaceName() path.String {
	return instance.tablespaceName
}

func Engine() path.String {
	return instance.engine
}

func TablespaceType() path.String {
	return instance.tablespaceType
}

func LogfileGroupName() path.String {
	return instance.logfileGroupName
}

func ExtentSize() path.Int64 {
	return instance.extentSize
}

func AutoextendSize() path.Int64 {
	return instance.autoextendSize
}

func MaximumSize() path.Int64 {
	return instance.maximumSize
}

func NodegroupId() path.Int64 {
	return instance.nodegroupId
}

func TablespaceComment() path.String {
	return instance.tablespaceComment
}
