// Code generated by Lingo for table information_schema.INNODB_LOCKS - DO NOT EDIT

package qinnodblocks

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QInnodbLocks {
	return newQInnodbLocks(alias)
}

func New() QInnodbLocks {
	return newQInnodbLocks("")
}

func newQInnodbLocks(alias string) QInnodbLocks {
	q := QInnodbLocks{_alias: alias}
	q.lockId = path.NewStringPath(q, "lock_id")
	q.lockTrxId = path.NewStringPath(q, "lock_trx_id")
	q.lockMode = path.NewStringPath(q, "lock_mode")
	q.lockType = path.NewStringPath(q, "lock_type")
	q.lockTable = path.NewStringPath(q, "lock_table")
	q.lockIndex = path.NewStringPath(q, "lock_index")
	q.lockSpace = path.NewInt64Path(q, "lock_space")
	q.lockPage = path.NewInt64Path(q, "lock_page")
	q.lockRec = path.NewInt64Path(q, "lock_rec")
	q.lockData = path.NewStringPath(q, "lock_data")
	return q
}

type QInnodbLocks struct {
	_alias    string
	lockId    path.String
	lockTrxId path.String
	lockMode  path.String
	lockType  path.String
	lockTable path.String
	lockIndex path.String
	lockSpace path.Int64
	lockPage  path.Int64
	lockRec   path.Int64
	lockData  path.String
}

// core.Table Functions

func (q QInnodbLocks) GetColumns() []core.Column {
	return []core.Column{
		q.lockId,
		q.lockTrxId,
		q.lockMode,
		q.lockType,
		q.lockTable,
		q.lockIndex,
		q.lockSpace,
		q.lockPage,
		q.lockRec,
		q.lockData,
	}
}

func (q QInnodbLocks) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QInnodbLocks) GetAlias() string {
	return q._alias
}

func (q QInnodbLocks) GetName() string {
	return "INNODB_LOCKS"
}

func (q QInnodbLocks) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QInnodbLocks) LockId() path.String {
	return q.lockId
}

func (q QInnodbLocks) LockTrxId() path.String {
	return q.lockTrxId
}

func (q QInnodbLocks) LockMode() path.String {
	return q.lockMode
}

func (q QInnodbLocks) LockType() path.String {
	return q.lockType
}

func (q QInnodbLocks) LockTable() path.String {
	return q.lockTable
}

func (q QInnodbLocks) LockIndex() path.String {
	return q.lockIndex
}

func (q QInnodbLocks) LockSpace() path.Int64 {
	return q.lockSpace
}

func (q QInnodbLocks) LockPage() path.Int64 {
	return q.lockPage
}

func (q QInnodbLocks) LockRec() path.Int64 {
	return q.lockRec
}

func (q QInnodbLocks) LockData() path.String {
	return q.lockData
}
