// Code generated by Lingo for table sakila.film_text - DO NOT EDIT

// +build !nolingo

package tfilmtext

import (
	"github.com/weworksandbox/lingo/expr"
)

var instance = New()

func T() TFilmText {
	return instance
}

func FilmId() expr.Int16 {
	return instance.FilmId()
}

func Title() expr.String {
	return instance.Title()
}

func Description() expr.String {
	return instance.Description()
}
