// Code generated by Lingo for table sakila.film_text - DO NOT EDIT

// +build !nolingo

package tfilmtext

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr/path"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) TFilmText {
	return newTFilmText(alias)
}

func New() TFilmText {
	return newTFilmText("")
}

func newTFilmText(alias string) TFilmText {
	t := TFilmText{
		_alias: alias,
	}
	t.filmId = path.NewInt16(t, "film_id")
	t.title = path.NewString(t, "title")
	t.description = path.NewString(t, "description")
	return t
}

type TFilmText struct {
	_alias string

	filmId      path.Int16
	title       path.String
	description path.String
}

// lingo.Table Functions

func (t TFilmText) GetColumns() []lingo.Column {
	return []lingo.Column{
		t.filmId,
		t.title,
		t.description,
	}
}

func (t TFilmText) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return path.ExpandTableWithDialect(d, t)
}

func (t TFilmText) GetAlias() string {
	return t._alias
}

func (t TFilmText) GetName() string {
	return "film_text"
}

func (t TFilmText) GetParent() string {
	return "sakila"
}

// Column Functions

func (t TFilmText) FilmId() path.Int16 {
	return t.filmId
}

func (t TFilmText) Title() path.String {
	return t.title
}

func (t TFilmText) Description() path.String {
	return t.description
}
