// Code generated by Lingo for table information_schema.INNODB_SESSION_TEMP_TABLESPACES - DO NOT EDIT

package qinnodbsessiontemptablespaces

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QInnodbSessionTempTablespaces {
	return instance
}

func Id() path.IntPath {
	return instance.id
}

func Space() path.IntPath {
	return instance.space
}

func Path() path.StringPath {
	return instance.path
}

func Size() path.Int64Path {
	return instance.size
}

func State() path.StringPath {
	return instance.state
}

func Purpose() path.StringPath {
	return instance.purpose
}
