// Code generated by Lingo for table sakila.film - DO NOT EDIT

// +build !nolingo

package tfilm

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) TFilm {
	t := New()
	if alias != "" {
		t.alias = expr.Lit(alias)
	}
	return t
}

func New() TFilm {
	return TFilm{}
}

type TFilm struct {
	alias lingo.Expression
}

// lingo.Table Functions

func (t TFilm) GetTableName() string {
	return "film"
}

func (t TFilm) GetColumns() []lingo.Expression {
	return []lingo.Expression{
		t.FilmId(),
		t.Title(),
		t.Description(),
		t.ReleaseYear(),
		t.LanguageId(),
		t.OriginalLanguageId(),
		t.RentalDuration(),
		t.RentalRate(),
		t.Length(),
		t.ReplacementCost(),
		t.Rating(),
		t.SpecialFeatures(),
		t.LastUpdate(),
	}
}

func (t TFilm) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return expr.Table(t).ToSQL(d)
}

func (t TFilm) GetName() lingo.Expression {
	return expr.TableName(t)
}

func (t TFilm) GetAlias() lingo.Expression {
	return t.alias
}

// Column Functions

func (t TFilm) FilmId() expr.Int16 {
	return expr.Column(t, expr.Lit("film_id")).ToSQL
}

func (t TFilm) Title() expr.String {
	return expr.Column(t, expr.Lit("title")).ToSQL
}

func (t TFilm) Description() expr.String {
	return expr.Column(t, expr.Lit("description")).ToSQL
}

func (t TFilm) ReleaseYear() expr.UnsupportedType {
	return expr.Column(t, expr.Lit("release_year")).ToSQL
}

func (t TFilm) LanguageId() expr.Int8 {
	return expr.Column(t, expr.Lit("language_id")).ToSQL
}

func (t TFilm) OriginalLanguageId() expr.Int8 {
	return expr.Column(t, expr.Lit("original_language_id")).ToSQL
}

func (t TFilm) RentalDuration() expr.Int8 {
	return expr.Column(t, expr.Lit("rental_duration")).ToSQL
}

func (t TFilm) RentalRate() expr.Binary {
	return expr.Column(t, expr.Lit("rental_rate")).ToSQL
}

func (t TFilm) Length() expr.Int16 {
	return expr.Column(t, expr.Lit("length")).ToSQL
}

func (t TFilm) ReplacementCost() expr.Binary {
	return expr.Column(t, expr.Lit("replacement_cost")).ToSQL
}

func (t TFilm) Rating() expr.String {
	return expr.Column(t, expr.Lit("rating")).ToSQL
}

func (t TFilm) SpecialFeatures() expr.String {
	return expr.Column(t, expr.Lit("special_features")).ToSQL
}

func (t TFilm) LastUpdate() expr.Time {
	return expr.Column(t, expr.Lit("last_update")).ToSQL
}
