// Code generated by Lingo for table information_schema.USER_PRIVILEGES - DO NOT EDIT

package quserprivileges

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QUserPrivileges {
	return instance
}

func Grantee() path.StringPath {
	return instance.grantee
}

func TableCatalog() path.StringPath {
	return instance.tableCatalog
}

func PrivilegeType() path.StringPath {
	return instance.privilegeType
}

func IsGrantable() path.StringPath {
	return instance.isGrantable
}
