// Code generated by Lingo for table sakila.sales_by_film_category - DO NOT EDIT

// +build !nolingo

package tsalesbyfilmcategory

import (
	"github.com/weworksandbox/lingo/expr"
)

var instance = New()

func T() TSalesByFilmCategory {
	return instance
}

func Category() expr.String {
	return instance.Category()
}

func TotalSales() expr.Binary {
	return instance.TotalSales()
}
