// Code generated by Lingo for table information_schema.INNODB_LOCK_WAITS - DO NOT EDIT

package qinnodblockwaits

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbLockWaits {
	return instance
}

func RequestingTrxId() path.String {
	return instance.requestingTrxId
}

func RequestedLockId() path.String {
	return instance.requestedLockId
}

func BlockingTrxId() path.String {
	return instance.blockingTrxId
}

func BlockingLockId() path.String {
	return instance.blockingLockId
}
