// Code generated by Lingo for table sakila.country - DO NOT EDIT

package qcountry

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QCountry {
	return instance
}

func CountryId() path.Int16Path {
	return instance.countryId
}

func Country() path.StringPath {
	return instance.country
}

func LastUpdate() path.TimePath {
	return instance.lastUpdate
}
