// Code generated by Lingo for table information_schema.INNODB_SYS_FIELDS - DO NOT EDIT

package qinnodbsysfields

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbSysFields {
	return instance
}

func IndexId() path.Int64Path {
	return instance.indexId
}

func Name() path.StringPath {
	return instance.name
}

func Pos() path.IntPath {
	return instance.pos
}
