// Code generated by Lingo for table information_schema.INNODB_METRICS - DO NOT EDIT

package qinnodbmetrics

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbMetrics {
	return instance
}

func Name() path.String {
	return instance.name
}

func Subsystem() path.String {
	return instance.subsystem
}

func Count() path.Int64 {
	return instance.count
}

func MaxCount() path.Int64 {
	return instance.maxCount
}

func MinCount() path.Int64 {
	return instance.minCount
}

func AvgCount() path.Float64 {
	return instance.avgCount
}

func CountReset() path.Int64 {
	return instance.countReset
}

func MaxCountReset() path.Int64 {
	return instance.maxCountReset
}

func MinCountReset() path.Int64 {
	return instance.minCountReset
}

func AvgCountReset() path.Float64 {
	return instance.avgCountReset
}

func TimeEnabled() path.Time {
	return instance.timeEnabled
}

func TimeDisabled() path.Time {
	return instance.timeDisabled
}

func TimeElapsed() path.Int64 {
	return instance.timeElapsed
}

func TimeReset() path.Time {
	return instance.timeReset
}

func Status() path.String {
	return instance.status
}

func Type() path.String {
	return instance.__type
}

func Comment() path.String {
	return instance.comment
}
