// Code generated by Lingo for table sakila.sales_by_store - DO NOT EDIT

package qsalesbystore

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QSalesByStore {
	return newQSalesByStore(alias)
}

func New() QSalesByStore {
	return newQSalesByStore("")
}

func newQSalesByStore(alias string) QSalesByStore {
	q := QSalesByStore{_alias: alias}
	q.store = path.NewStringPath(q, "store")
	q.manager = path.NewStringPath(q, "manager")
	q.totalSales = path.NewBinaryPath(q, "total_sales")
	return q
}

type QSalesByStore struct {
	_alias     string
	store      path.StringPath
	manager    path.StringPath
	totalSales path.BinaryPath
}

// core.Table Functions

func (q QSalesByStore) GetColumns() []core.Column {
	return []core.Column{
		q.store,
		q.manager,
		q.totalSales,
	}
}

func (q QSalesByStore) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QSalesByStore) GetAlias() string {
	return q._alias
}

func (q QSalesByStore) GetName() string {
	return "sales_by_store"
}

func (q QSalesByStore) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QSalesByStore) Store() path.StringPath {
	return q.store
}

func (q QSalesByStore) Manager() path.StringPath {
	return q.manager
}

func (q QSalesByStore) TotalSales() path.BinaryPath {
	return q.totalSales
}
