// Code generated by Lingo for table sakila.inventory - DO NOT EDIT

// +build !nolingo

package tinventory

import (
	"github.com/weworksandbox/lingo"
	"github.com/weworksandbox/lingo/expr"
	"github.com/weworksandbox/lingo/sql"
)

func As(alias string) TInventory {
	t := New()
	if alias != "" {
		t.alias = expr.Lit(alias)
	}
	return t
}

func New() TInventory {
	return TInventory{}
}

type TInventory struct {
	alias lingo.Expression
}

// lingo.Table Functions

func (t TInventory) GetTableName() string {
	return "inventory"
}

func (t TInventory) GetColumns() []lingo.Expression {
	return []lingo.Expression{
		t.InventoryId(),
		t.FilmId(),
		t.StoreId(),
		t.LastUpdate(),
	}
}

func (t TInventory) ToSQL(d lingo.Dialect) (sql.Data, error) {
	return expr.Table(t).ToSQL(d)
}

func (t TInventory) GetName() lingo.Expression {
	return expr.TableName(t)
}

func (t TInventory) GetAlias() lingo.Expression {
	return t.alias
}

// Column Functions

func (t TInventory) InventoryId() expr.Int32 {
	return expr.Column(t, expr.Lit("inventory_id")).ToSQL
}

func (t TInventory) FilmId() expr.Int16 {
	return expr.Column(t, expr.Lit("film_id")).ToSQL
}

func (t TInventory) StoreId() expr.Int8 {
	return expr.Column(t, expr.Lit("store_id")).ToSQL
}

func (t TInventory) LastUpdate() expr.Time {
	return expr.Column(t, expr.Lit("last_update")).ToSQL
}
