// Code generated by Lingo for table information_schema.VIEW_TABLE_USAGE - DO NOT EDIT

package qviewtableusage

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QViewTableUsage {
	return instance
}

func ViewCatalog() path.StringPath {
	return instance.viewCatalog
}

func ViewSchema() path.StringPath {
	return instance.viewSchema
}

func ViewName() path.StringPath {
	return instance.viewName
}

func TableCatalog() path.StringPath {
	return instance.tableCatalog
}

func TableSchema() path.StringPath {
	return instance.tableSchema
}

func TableName() path.StringPath {
	return instance.tableName
}
