// Code generated by Lingo for table sakila.staff - DO NOT EDIT

package qstaff

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QStaff {
	return instance
}

func StaffId() path.Int8Path {
	return instance.staffId
}

func FirstName() path.StringPath {
	return instance.firstName
}

func LastName() path.StringPath {
	return instance.lastName
}

func AddressId() path.Int16Path {
	return instance.addressId
}

func Picture() path.UnsupportedPath {
	return instance.picture
}

func Email() path.StringPath {
	return instance.email
}

func StoreId() path.Int8Path {
	return instance.storeId
}

func Active() path.Int8Path {
	return instance.active
}

func Username() path.StringPath {
	return instance.username
}

func Password() path.StringPath {
	return instance.password
}

func LastUpdate() path.TimePath {
	return instance.lastUpdate
}
