// Code generated by Lingo for table sakila.staff - DO NOT EDIT

package qstaff

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QStaff {
	return newQStaff(alias)
}

func New() QStaff {
	return newQStaff("")
}

func newQStaff(alias string) QStaff {
	q := QStaff{_alias: alias}
	q.staffId = path.NewInt8Path(q, "staff_id")
	q.firstName = path.NewStringPath(q, "first_name")
	q.lastName = path.NewStringPath(q, "last_name")
	q.addressId = path.NewInt16Path(q, "address_id")
	q.picture = path.NewUnsupportedPath(q, "picture")
	q.email = path.NewStringPath(q, "email")
	q.storeId = path.NewInt8Path(q, "store_id")
	q.active = path.NewInt8Path(q, "active")
	q.username = path.NewStringPath(q, "username")
	q.password = path.NewStringPath(q, "password")
	q.lastUpdate = path.NewTimePath(q, "last_update")
	return q
}

type QStaff struct {
	_alias     string
	staffId    path.Int8
	firstName  path.String
	lastName   path.String
	addressId  path.Int16
	picture    path.Unsupported
	email      path.String
	storeId    path.Int8
	active     path.Int8
	username   path.String
	password   path.String
	lastUpdate path.Time
}

// core.Table Functions

func (q QStaff) GetColumns() []core.Column {
	return []core.Column{
		q.staffId,
		q.firstName,
		q.lastName,
		q.addressId,
		q.picture,
		q.email,
		q.storeId,
		q.active,
		q.username,
		q.password,
		q.lastUpdate,
	}
}

func (q QStaff) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QStaff) GetAlias() string {
	return q._alias
}

func (q QStaff) GetName() string {
	return "staff"
}

func (q QStaff) GetParent() string {
	return "sakila"
}

// Column Functions

func (q QStaff) StaffId() path.Int8 {
	return q.staffId
}

func (q QStaff) FirstName() path.String {
	return q.firstName
}

func (q QStaff) LastName() path.String {
	return q.lastName
}

func (q QStaff) AddressId() path.Int16 {
	return q.addressId
}

func (q QStaff) Picture() path.Unsupported {
	return q.picture
}

func (q QStaff) Email() path.String {
	return q.email
}

func (q QStaff) StoreId() path.Int8 {
	return q.storeId
}

func (q QStaff) Active() path.Int8 {
	return q.active
}

func (q QStaff) Username() path.String {
	return q.username
}

func (q QStaff) Password() path.String {
	return q.password
}

func (q QStaff) LastUpdate() path.Time {
	return q.lastUpdate
}
