// Code generated by Lingo for table information_schema.INNODB_CMPMEM - DO NOT EDIT

package qinnodbcmpmem

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbCmpmem {
	return instance
}

func PageSize() path.Int {
	return instance.pageSize
}

func BufferPoolInstance() path.Int {
	return instance.bufferPoolInstance
}

func PagesUsed() path.Int {
	return instance.pagesUsed
}

func PagesFree() path.Int {
	return instance.pagesFree
}

func RelocationOps() path.Int64 {
	return instance.relocationOps
}

func RelocationTime() path.Int {
	return instance.relocationTime
}
