// Code generated by Lingo for table information_schema.EVENTS - DO NOT EDIT

package qevents

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QEvents {
	return instance
}

func EventCatalog() path.String {
	return instance.eventCatalog
}

func EventSchema() path.String {
	return instance.eventSchema
}

func EventName() path.String {
	return instance.eventName
}

func Definer() path.String {
	return instance.definer
}

func TimeZone() path.String {
	return instance.timeZone
}

func EventBody() path.String {
	return instance.eventBody
}

func EventDefinition() path.String {
	return instance.eventDefinition
}

func EventType() path.String {
	return instance.eventType
}

func ExecuteAt() path.Time {
	return instance.executeAt
}

func IntervalValue() path.String {
	return instance.intervalValue
}

func IntervalField() path.String {
	return instance.intervalField
}

func SqlMode() path.String {
	return instance.sqlMode
}

func Starts() path.Time {
	return instance.starts
}

func Ends() path.Time {
	return instance.ends
}

func Status() path.String {
	return instance.status
}

func OnCompletion() path.String {
	return instance.onCompletion
}

func Created() path.Time {
	return instance.created
}

func LastAltered() path.Time {
	return instance.lastAltered
}

func LastExecuted() path.Time {
	return instance.lastExecuted
}

func EventComment() path.String {
	return instance.eventComment
}

func Originator() path.Int64 {
	return instance.originator
}

func CharacterSetClient() path.String {
	return instance.characterSetClient
}

func CollationConnection() path.String {
	return instance.collationConnection
}

func DatabaseCollation() path.String {
	return instance.databaseCollation
}
