// Code generated by Lingo for table information_schema.ROUTINES - DO NOT EDIT

package qroutines

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QRoutines {
	return instance
}

func SpecificName() path.StringPath {
	return instance.specificName
}

func RoutineCatalog() path.StringPath {
	return instance.routineCatalog
}

func RoutineSchema() path.StringPath {
	return instance.routineSchema
}

func RoutineName() path.StringPath {
	return instance.routineName
}

func RoutineType() path.StringPath {
	return instance.routineType
}

func DataType() path.StringPath {
	return instance.dataType
}

func CharacterMaximumLength() path.IntPath {
	return instance.characterMaximumLength
}

func CharacterOctetLength() path.IntPath {
	return instance.characterOctetLength
}

func NumericPrecision() path.Int64Path {
	return instance.numericPrecision
}

func NumericScale() path.IntPath {
	return instance.numericScale
}

func DatetimePrecision() path.Int64Path {
	return instance.datetimePrecision
}

func CharacterSetName() path.StringPath {
	return instance.characterSetName
}

func CollationName() path.StringPath {
	return instance.collationName
}

func DtdIdentifier() path.StringPath {
	return instance.dtdIdentifier
}

func RoutineBody() path.StringPath {
	return instance.routineBody
}

func RoutineDefinition() path.StringPath {
	return instance.routineDefinition
}

func ExternalName() path.StringPath {
	return instance.externalName
}

func ExternalLanguage() path.StringPath {
	return instance.externalLanguage
}

func ParameterStyle() path.StringPath {
	return instance.parameterStyle
}

func IsDeterministic() path.StringPath {
	return instance.isDeterministic
}

func SqlDataAccess() path.StringPath {
	return instance.sqlDataAccess
}

func SqlPath() path.StringPath {
	return instance.sqlPath
}

func SecurityType() path.StringPath {
	return instance.securityType
}

func Created() path.TimePath {
	return instance.created
}

func LastAltered() path.TimePath {
	return instance.lastAltered
}

func SqlMode() path.StringPath {
	return instance.sqlMode
}

func RoutineComment() path.StringPath {
	return instance.routineComment
}

func Definer() path.StringPath {
	return instance.definer
}

func CharacterSetClient() path.StringPath {
	return instance.characterSetClient
}

func CollationConnection() path.StringPath {
	return instance.collationConnection
}

func DatabaseCollation() path.StringPath {
	return instance.databaseCollation
}
