package generator

import (
	"io"
)

const (
	GenPathFileHeader = "// Code generated by an internal Lingo tool, genpaths.go - DO NOT EDIT"
)

type Ops struct {
	Set, Equality, Comparison, Nullable, In, Between bool
}

type Path struct {
	Name       string
	Filename   string
	GoType     string
	Imports    []string
	Operations Ops
}

func (p Path) Generate() (io.Reader, error) {
	return generateFromTemplate(pathTemplate, p)
}
