// Code generated by Lingo for table sakila.city - DO NOT EDIT

package qcity

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QCity {
	return instance
}

func CityId() path.Int16 {
	return instance.cityId
}

func City() path.String {
	return instance.city
}

func CountryId() path.Int16 {
	return instance.countryId
}

func LastUpdate() path.Time {
	return instance.lastUpdate
}
