// Code generated by Lingo for table sakila.nicer_but_slower_film_list - DO NOT EDIT

// +build !nolingo

package tnicerbutslowerfilmlist

import (
	"github.com/weworksandbox/lingo/expr/path"
)

var instance = New()

func T() TNicerButSlowerFilmList {
	return instance
}

func FID() path.Int16 {
	return instance.fID
}

func Title() path.String {
	return instance.title
}

func Description() path.String {
	return instance.description
}

func Category() path.String {
	return instance.category
}

func Price() path.Binary {
	return instance.price
}

func Length() path.Int16 {
	return instance.length
}

func Rating() path.String {
	return instance.rating
}

func Actors() path.String {
	return instance.actors
}
