// Code generated by Lingo for table information_schema.INNODB_FT_DEFAULT_STOPWORD - DO NOT EDIT

package qinnodbftdefaultstopword

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbFtDefaultStopword {
	return instance
}

func Value() path.StringPath {
	return instance.value
}
