// Code generated by Lingo for table information_schema.INNODB_FT_DEFAULT_STOPWORD - DO NOT EDIT

package qinnodbftdefaultstopword

import (
	"github.com/weworksandbox/lingo/pkg/core"
	"github.com/weworksandbox/lingo/pkg/core/path"
)

func As(alias string) QInnodbFtDefaultStopword {
	return newQInnodbFtDefaultStopword(alias)
}

func New() QInnodbFtDefaultStopword {
	return newQInnodbFtDefaultStopword("")
}

func newQInnodbFtDefaultStopword(alias string) QInnodbFtDefaultStopword {
	q := QInnodbFtDefaultStopword{_alias: alias}
	q.value = path.NewStringPath(q, "value")
	return q
}

type QInnodbFtDefaultStopword struct {
	_alias string
	value  path.String
}

// core.Table Functions

func (q QInnodbFtDefaultStopword) GetColumns() []core.Column {
	return []core.Column{
		q.value,
	}
}

func (q QInnodbFtDefaultStopword) GetSQL(d core.Dialect) (core.SQL, error) {
	return path.ExpandTableWithDialect(d, q)
}

func (q QInnodbFtDefaultStopword) GetAlias() string {
	return q._alias
}

func (q QInnodbFtDefaultStopword) GetName() string {
	return "INNODB_FT_DEFAULT_STOPWORD"
}

func (q QInnodbFtDefaultStopword) GetParent() string {
	return "information_schema"
}

// Column Functions

func (q QInnodbFtDefaultStopword) Value() path.String {
	return q.value
}
