// Code generated by Lingo for table information_schema.INNODB_SYS_FOREIGN - DO NOT EDIT

package qinnodbsysforeign

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QInnodbSysForeign {
	return instance
}

func Id() path.String {
	return instance.id
}

func ForName() path.String {
	return instance.forName
}

func RefName() path.String {
	return instance.refName
}

func NCols() path.Int {
	return instance.nCols
}

func Type() path.Int {
	return instance.__type
}
