// Code generated by Lingo for table information_schema.INNODB_TABLESPACES - DO NOT EDIT

package qinnodbtablespaces

import "github.com/weworksandbox/lingo/core/path"

var instance = New()

func Q() QInnodbTablespaces {
	return instance
}

func Space() path.IntPath {
	return instance.space
}

func Name() path.StringPath {
	return instance.name
}

func Flag() path.IntPath {
	return instance.flag
}

func RowFormat() path.StringPath {
	return instance.rowFormat
}

func PageSize() path.IntPath {
	return instance.pageSize
}

func ZipPageSize() path.IntPath {
	return instance.zipPageSize
}

func SpaceType() path.StringPath {
	return instance.spaceType
}

func FsBlockSize() path.IntPath {
	return instance.fsBlockSize
}

func FileSize() path.Int64Path {
	return instance.fileSize
}

func AllocatedSize() path.Int64Path {
	return instance.allocatedSize
}

func ServerVersion() path.StringPath {
	return instance.serverVersion
}

func SpaceVersion() path.IntPath {
	return instance.spaceVersion
}

func Encryption() path.StringPath {
	return instance.encryption
}

func State() path.StringPath {
	return instance.state
}
