name: Go Build

on: [push, pull_request]

jobs:
  build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download -x

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -count=1 -covermode=atomic -coverprofile=coverage.out -tags -acceptance -ginkgo.randomizeAllSpecs ./...

    - uses: codecov/codecov-action@v1
      with:
#        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage.out # optional
        flags: unittests # optional
#        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
