# This will auto format our code, then re-commit the code back to that PR. It only runs on PRs.

name: Golang Formatter
on: [pull_request]
jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Golang Formatter
        uses: sladyn98/auto-go-format@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
