# This will auto lint our Go code. It only runs on PRs.

name: Golang Lint
on: [pull_request]
jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Golang Lint
        uses: Jerome1337/golint-action@v1.0.0
        with:
          golint-path: './...'
