// Code generated by Lingo for table information_schema.SESSION_STATUS - DO NOT EDIT

package qsessionstatus

import "github.com/weworksandbox/lingo/pkg/core/path"

var instance = New()

func Q() QSessionStatus {
	return instance
}

func VariableName() path.StringPath {
	return instance.variableName
}

func VariableValue() path.StringPath {
	return instance.variableValue
}
